// TỆP SINH TỰ ĐỘNG — đừng sửa bằng tay.
// Nguồn: src/app/core/topics/topic-list.ts + data-source/<bài>/vocabulary*.txt
// Sinh lại: npm run generate:topics
//
// PHẦN NHẸ: đủ để vẽ thẻ chủ đề và để LessonStore biết có những chủ đề nào,
// mà không phải nạp một từ vựng nào. Nhập thẳng được ở mọi nơi.

import type { TopicCatalogEntry } from './topic.model';

export const TOPIC_CATALOG: readonly TopicCatalogEntry[] = [
  {
    id: 'gia-dinh',
    japanese: '家族・人間関係',
    vietnamese: 'Gia đình & quan hệ',
    description: 'Xưng hô trong nhà, họ hàng, bạn bè, cưới xin — nhóm từ có mặt ở hầu hết bài đọc N3.',
    icon: '👨‍👩‍👧',
    wordCount: 63,
    sourceCount: 22,
  },
  {
    id: 'co-the-suc-khoe',
    japanese: '体・健康・病気',
    vietnamese: 'Cơ thể, sức khoẻ & bệnh tật',
    description: 'Bộ phận cơ thể, triệu chứng, bệnh viện và cách nói về tình trạng sức khoẻ.',
    icon: '🩺',
    wordCount: 63,
    sourceCount: 27,
  },
  {
    id: 'thien-nhien-thoi-tiet',
    japanese: '自然・天気',
    vietnamese: 'Thiên nhiên & thời tiết',
    description: 'Mây, gió, núi, biển, bốn mùa và các hiện tượng thời tiết — chủ đề ruột của bài đọc.',
    icon: '🌤️',
    wordCount: 49,
    sourceCount: 21,
  },
  {
    id: 'dong-vat-thuc-vat',
    japanese: '動物・植物',
    vietnamese: 'Động vật & cây cỏ',
    description: 'Con vật nuôi, cây cối, hoa lá và những việc làm đi kèm: nuôi, trồng, cho ăn.',
    icon: '🐕',
    wordCount: 34,
    sourceCount: 15,
  },
  {
    id: 'nha-cua-do-dung',
    japanese: '家・家具・日用品',
    vietnamese: 'Nhà cửa & đồ dùng trong nhà',
    description: 'Các phòng, đồ nội thất, đồ điện và việc nhà — phần lớn lấy từ 総まとめ N3 tuần 1.',
    icon: '🏠',
    wordCount: 60,
    sourceCount: 21,
  },
  {
    id: 'an-uong-nau-an',
    japanese: '食べ物・料理',
    vietnamese: 'Ăn uống & nấu nướng',
    description: 'Món ăn, nguyên liệu, gia vị, dụng cụ bếp và các động từ nấu: luộc, xào, hấp, chiên.',
    icon: '🍳',
    wordCount: 72,
    sourceCount: 18,
  },
  {
    id: 'quan-ao-do-dung',
    japanese: '衣類・持ち物',
    vietnamese: 'Quần áo & đồ mang theo',
    description: 'Quần áo, phụ kiện, đồ trong túi xách, kèm các động từ mặc/đội/đeo đi với từng loại.',
    icon: '👕',
    wordCount: 38,
    sourceCount: 20,
  },
  {
    id: 'phuong-huong-vi-tri',
    japanese: '方向・位置',
    vietnamese: 'Phương hướng & vị trí',
    description: 'Trên dưới trước sau, bốn phương, và những từ chỉ chỗ hay gặp trong câu chỉ đường.',
    icon: '🧭',
    wordCount: 38,
    sourceCount: 15,
  },
  {
    id: 'giao-thong-di-lai',
    japanese: '交通・乗り物',
    vietnamese: 'Giao thông & đi lại',
    description: 'Phương tiện, nhà ga, đường sá, cùng các động từ lên/xuống/đổi tàu và chuyện tai nạn.',
    icon: '🚃',
    wordCount: 56,
    sourceCount: 23,
  },
  {
    id: 'du-lich-giai-tri',
    japanese: '旅行・レジャー',
    vietnamese: 'Du lịch & giải trí',
    description: 'Đi chơi, đặt phòng, thể thao, âm nhạc, phim ảnh — chuyện đời sống ngoài giờ làm.',
    icon: '🧳',
    wordCount: 53,
    sourceCount: 22,
  },
  {
    id: 'cong-viec-cong-ty',
    japanese: '仕事・会社',
    vietnamese: 'Công việc & công ty',
    description: 'Chức danh, phòng ban, họp hành, giấy tờ và cách nói về lịch làm việc.',
    icon: '💼',
    wordCount: 58,
    sourceCount: 29,
  },
  {
    id: 'truong-hoc-hoc-tap',
    japanese: '学校・勉強',
    vietnamese: 'Trường học & học tập',
    description: 'Cấp học, giờ học, thi cử và những động từ đi với việc học: ôn, nhớ, quên, hỏi.',
    icon: '🎓',
    wordCount: 61,
    sourceCount: 32,
  },
  {
    id: 'mua-sam-tien-bac',
    japanese: '買い物・お金',
    vietnamese: 'Mua sắm & tiền bạc',
    description: 'Cửa hàng, giá cả, trả tiền, gửi bưu điện — nhóm từ hay ra ở phần nghe hội thoại.',
    icon: '🛒',
    wordCount: 53,
    sourceCount: 29,
  },
  {
    id: 'thanh-pho-cong-cong',
    japanese: '町・公共施設',
    vietnamese: 'Phố xá & nơi công cộng',
    description: 'Địa danh, cơ quan, biển báo trong thành phố và các từ về trật tự xã hội.',
    icon: '🏙️',
    wordCount: 58,
    sourceCount: 25,
  },
  {
    id: 'thoi-gian-ngay-thang',
    japanese: '時間・日付',
    vietnamese: 'Thời gian & ngày tháng',
    description: 'Buổi trong ngày, thứ, tuần, tháng, năm và những từ chỉ mốc: đầu tiên, cuối cùng, gần đây.',
    icon: '🕒',
    wordCount: 63,
    sourceCount: 21,
  },
  {
    id: 'so-luong-don-vi',
    japanese: '数・量・単位',
    vietnamese: 'Số lượng & đơn vị',
    description: 'Số lớn, đơn vị đếm, cách đo lường và các cặp tăng/giảm — phần dễ mất điểm vì đọc lướt.',
    icon: '🔢',
    wordCount: 52,
    sourceCount: 17,
  },
  {
    id: 'cam-xuc-tinh-cach',
    japanese: '気持ち・性格',
    vietnamese: 'Cảm xúc & tính cách',
    description: 'Vui buồn lo sợ, tính nết con người — nhóm tính từ mà bài đọc N3 dùng để tả nhân vật.',
    icon: '💭',
    wordCount: 62,
    sourceCount: 24,
  },
  {
    id: 'tu-tha-dong-tu',
    japanese: '自動詞・他動詞',
    vietnamese: 'Tự động từ & tha động từ',
    description: 'Các cặp nội/ngoại động từ xếp cạnh nhau. Đề N3 hỏi rất nhiều ở dạng chọn trợ từ が/を.',
    icon: '🔁',
    wordCount: 74,
    sourceCount: 25,
  },
  {
    id: 'trang-tu-cach-noi',
    japanese: '副詞・表現',
    vietnamese: 'Trạng từ & cách nói',
    description: 'Từ bổ nghĩa và các cụm nối câu. Chúng quyết định nghĩa cả câu nên hay bị đem ra hỏi.',
    icon: '✏️',
    wordCount: 49,
    sourceCount: 28,
  },
  {
    id: 'chao-hoi-kinh-ngu',
    japanese: 'あいさつ・敬語',
    vietnamese: 'Chào hỏi & kính ngữ',
    description: 'Mẫu câu giao tiếp cố định, kèm bảng tôn kính ngữ / khiêm nhường ngữ của bài 49–50.',
    icon: '🙇',
    wordCount: 41,
    sourceCount: 17,
  },
];
