// TỆP SINH TỰ ĐỘNG — đừng sửa bằng tay.
// Nguồn: src/app/core/topics/topic-list.ts + data-source/<bài>/vocabulary*.txt
// Sinh lại: npm run generate:topics
//
// PHẦN NẶNG: mỗi dòng là [tiếng Nhật, cách đọc, âm Hán Việt, nghĩa, câu ví dụ,
// id bài gốc]. Chỉ được nhập ĐỘNG (xem topic-entries.ts) để trang chủ khỏi phải
// tải toàn bộ từ vựng chủ đề khi nó chẳng hiện chủ đề nào.
//
// Toàn bộ nội dung ở đây được TRA từ kho từ của ứng dụng, không chép tay chữ nào.

import type { TopicSeed } from './topic.model';

export const TOPIC_SEEDS: readonly TopicSeed[] = [
  ['gia-dinh', [
    ['家族', 'かぞく', 'GIA TỘC', 'gia đình', '', 'minano-nihongo-5'],
    ['ご家族', 'ごかぞく', 'GIA TỘC', 'Gia đình', '', 'minano-nihongo-15'],
    ['両親', 'りょうしん', 'LƯỠNG THÂN', 'bố mẹ', '', 'minano-nihongo-11'],
    ['父', 'ちち', 'PHỤ', 'bố', '', 'minano-nihongo-7'],
    ['母', 'はは', 'MẪU', 'mẹ', '', 'minano-nihongo-7'],
    ['お父さん', 'おとうさん', 'PHỤ', 'bố', '', 'minano-nihongo-7'],
    ['お母さん', 'おかあさん', 'MẪU', 'Mẹ', '', 'minano-nihongo-7'],
    ['兄弟', 'きょうだい', 'HUYNH ĐỆ', 'anh chị em', '', 'minano-nihongo-11'],
    ['兄', 'あに', 'HUYNH', 'anh trai', '', 'minano-nihongo-11'],
    ['お兄さん', 'おにいさん', 'HUYNH', 'anh trai người khác', '', 'minano-nihongo-11'],
    ['姉', 'あね', 'TỶ', 'chị gái', '', 'minano-nihongo-11'],
    ['お姉さん', 'おねえさん', 'TỶ', 'chị gái', '', 'minano-nihongo-11'],
    ['弟', 'おとうと', 'ĐỆ', 'em trai', '', 'minano-nihongo-11'],
    ['弟さん', 'おとうとさん', 'ĐỆ', 'em trai', '', 'minano-nihongo-11'],
    ['妹', 'いもうと', 'MUỘI', 'em gái', '', 'minano-nihongo-11'],
    ['妹さん', 'いもうとさん', 'MUỘI', 'em gái', '', 'minano-nihongo-11'],
    ['姉妹', 'しまい', 'TỶ MUỘI', 'chị em (gái)', '姉妹はとてもよく似ています。', 'minano-nihongo-38'],
    ['祖父', 'そふ', 'TỔ PHỤ', 'ông (của mình)', '祖父に習字を教えてもらいました。', 'minano-nihongo-41'],
    ['祖母', 'そぼ', 'TỔ MẪU', 'bà (của mình)', '祖母が作ってくださったお菓子です。', 'minano-nihongo-41'],
    ['孫', 'まご', 'TÔN', 'cháu', '孫が生まれました。', 'minano-nihongo-41'],
    ['息子', 'むすこ', 'TỨC TỬ', 'con trai', '私の息子は大学生です。', 'minano-nihongo-28'],
    ['息子さん', 'むすこさん', 'TỨC TỬ', 'con trai (của người khác)', '息子さんはおいくつですか。', 'minano-nihongo-28'],
    ['娘', 'むすめ', 'NƯƠNG', 'con gái', '娘は学校へ行きます。', 'minano-nihongo-28'],
    ['娘さん', 'むすめさん', 'NƯƠNG', 'con gái (của người khác)', '娘さんは元気がいいですね。', 'minano-nihongo-28'],
    ['長男', 'ちょうなん', 'TRƯỜNG NAM', 'trưởng nam/ con trai cả', '長男は今年大学に入りました。', 'minano-nihongo-49'],
    ['夫', 'おっと', 'PHU', 'chồng', '', 'minano-nihongo-9'],
    ['主人', 'しゅじん', 'CHỦ NHÂN', 'chồng', '', 'minano-nihongo-9'],
    ['奥さん', 'おくさん', 'ÁO', 'vợ', '', 'minano-nihongo-9'],
    ['妻', 'つま', 'THÊ', 'vợ', '', 'minano-nihongo-9'],
    ['家内', 'かない', 'GIA NỘI', 'vợ', '', 'minano-nihongo-9'],
    ['子ども', 'こども', 'TỬ', 'con cái', '', 'minano-nihongo-9'],
    ['子どもたち', 'こどもたち', 'TỬ/TÝ', 'trẻ em/ trẻ con/ con cái', '公園で子どもたちが遊んでいます。', 'minano-nihongo-27'],
    ['子供たち', 'こどもたち', 'TỬ CUNG', 'trẻ em/ bọn trẻ', '子供たちにお菓子をあげました。', 'minano-nihongo-41'],
    ['お子さん', 'おこさん', 'TỬ', 'con (của người khác)', 'お子さんはおいくつですか。', 'minano-nihongo-30'],
    ['赤ちゃん', 'あかちゃん', 'XÍCH', 'em bé', '赤ちゃんが寝ています。', 'minano-nihongo-38'],
    ['双子', 'ふたご', 'SONG TỬ', 'cặp sinh đôi', 'あの二人は双子です。', 'minano-nihongo-38'],
    ['恋人', 'こいびと', 'LUYẾN NHÂN', 'người yêu', '恋人と映画を見に行きます。', 'minano-nihongo-32'],
    ['友達', 'ともだち', 'HỮU ĐẠT', 'bạn, bạn bè', '', 'minano-nihongo-5'],
    ['彼', 'かれ', 'BỈ', 'anh ấy, bạn trai', '', 'minano-nihongo-5'],
    ['彼女', 'かのじょ', 'BỈ NỮ', 'chị ấy, bạn gái', '', 'minano-nihongo-5'],
    ['仲間', 'なかま', 'TRỌNG GIAN', 'bạn bè/ đồng nghiệp', '仕事の仲間と食事しました。', 'minano-nihongo-37'],
    ['相手', 'あいて', 'TƯỚNG THỦ', 'đối tác/ đối phương', '結婚の相手を紹介されました。', 'minano-nihongo-47'],
    ['近所', 'きんじょ', 'CẬN SỞ', 'khu lân cận/ gần nhà', '近所に新しい店ができました。', 'minano-nihongo-35'],
    ['お宅', 'おたく', 'TRẠCH', 'nhà (của người khác)', '先生のお宅へ伺いました。', 'minano-nihongo-50'],
    ['大人', 'おとな', 'ĐẠI NHÂN', 'người lớn', '大人は千円、子どもは五百円です。', 'minano-nihongo-39'],
    ['男性', 'だんせい', 'NAM TÍNH', 'nam giới', '男性の声がしました。', 'minano-nihongo-47'],
    ['女性', 'じょせい', 'NỮ TÍNH', 'nữ giới', '女性の平均寿命は長いです。', 'minano-nihongo-47'],
    ['男の人', 'おとこのひと', 'NAM NHÂN', 'người đàn ông', '', 'minano-nihongo-10'],
    ['女の人', 'おんなのひと', 'NỮ NHÂN', 'người đàn bà', '', 'minano-nihongo-10'],
    ['男の子', 'おとこのこ', 'NAM TỬ', 'cậu con trai', '', 'minano-nihongo-10'],
    ['女の子', 'おんなのこ', 'NỮ TỬ', 'cô con gái', '', 'minano-nihongo-10'],
    ['男', 'おとこ', 'NAM', 'người đàn ông/ nam giới', '男の人が二人立っています。', 'minano-nihongo-41'],
    ['結婚します', 'けっこんします', 'KẾT HÔN', 'kết hôn, lập gia đình, cưới', '', 'minano-nihongo-13'],
    ['結婚式', 'けっこんしき', 'KẾT HÔN THỨC', 'lễ cưới/ đám cưới', '友達の結婚式に出席します。', 'minano-nihongo-31'],
    ['離婚します', 'りこんします', 'LY HÔN', 'ly dị/ ly hôn', '二人は去年離婚しました。', 'minano-nihongo-39'],
    ['婚約します', 'こんやくします', 'HÔN ƯỚC', 'đính hôn', '二人は婚約したそうです。', 'minano-nihongo-47'],
    ['お見合い', 'おみあい', 'KIẾN HỢP', 'xem mặt/ làm mối', 'お見合いで結婚しました。', 'minano-nihongo-39'],
    ['独身', 'どくしん', 'ĐỘC THÂN', 'Độc thân', '', 'minano-nihongo-15'],
    ['世話をします', 'せわをします', 'THẾ THOẠI', 'chăm sóc/ giúp đỡ', '子どもの世話をするのは大変です。', 'minano-nihongo-38'],
    ['似ています', 'にています', 'TỰ', 'giống', '母に似ていると言われます。', 'minano-nihongo-38'],
    ['知り合います', 'しりあいます', 'TRI HỢP', 'làm quen/ gặp gỡ làm quen', '二人は大学で知り合ったそうです。', 'minano-nihongo-47'],
    ['別れます', 'わかれます', 'BIỆT', 'chia tay/ từ biệt', '駅で友達と別れました。', 'minano-nihongo-44'],
    ['亡くなります', 'なくなります', 'VONG', 'mất/ qua đời', '祖父は去年亡くなりました。', 'minano-nihongo-33'],
  ]],
  ['co-the-suc-khoe', [
    ['体', 'からだ', 'THỂ', 'Người, cơ thể', '', 'minano-nihongo-16'],
    ['頭', 'あたま', 'ĐẦU', 'Đầu', '', 'minano-nihongo-16'],
    ['髪', 'かみ', 'PHÁT', 'Tóc', '', 'minano-nihongo-16'],
    ['顔', 'かお', 'NHAN', 'Mặt', '', 'minano-nihongo-16'],
    ['目', 'め', 'MỤC', 'Mắt', '', 'minano-nihongo-16'],
    ['耳', 'みみ', 'NHĨ', 'Tai', '', 'minano-nihongo-16'],
    ['口', 'くち', 'KHẨU', 'Miệng', '', 'minano-nihongo-16'],
    ['歯', 'は', 'XỈ', 'Răng', '', 'minano-nihongo-16'],
    ['足', 'あし', 'TÚC', 'Chân', '', 'minano-nihongo-16'],
    ['手', 'て', 'THỦ', 'tay', '', 'minano-nihongo-7'],
    ['胃', 'い', 'VỊ', 'dạ dày', '胃の調子が悪いです。', 'minano-nihongo-32'],
    ['心', 'こころ', 'TÂM', 'trái tim/ tấm lòng', '心から感謝しています。', 'minano-nihongo-48'],
    ['脳', 'のう', 'NÃO', 'não', '脳の働きを調べています。', 'minano-nihongo-47'],
    ['汗', 'あせ', 'HÃN', 'mồ hôi', '暑くて汗をかきました。', 'minano-nihongo-39'],
    ['涙', 'なみだ', 'LỆ', 'nước mắt', '涙が出ました。', 'minano-nihongo-44'],
    ['声', 'こえ', 'THANH', 'tiếng nói/ giọng nói', 'きれいな声ですね。', 'minano-nihongo-27'],
    ['姿', 'すがた', 'TƯ', 'dáng điệu/ hình dáng', '着物の姿が美しいです。', 'minano-nihongo-48'],
    ['病気', 'びょうき', 'BỆNH KHÍ', 'ốm, bệnh', '', 'minano-nihongo-17'],
    ['重い病気', 'おもいびょうき', 'TRỌNG BỆNH KHÍ', 'bệnh nặng', '父は重い病気で入院しています。', 'minano-nihongo-33'],
    ['熱', 'ねつ', 'NHIỆT', 'Sốt', '', 'minano-nihongo-17'],
    ['薬', 'くすり', 'DƯỢC', 'Thuốc', '', 'minano-nihongo-17'],
    ['傷', 'きず', 'THƯƠNG', 'vết thương', '手に傷ができました。', 'minano-nihongo-40'],
    ['食欲', 'しょくよく', 'THỰC DỤC', 'sự thèm ăn/ cảm giác muốn ăn', '暑くて食欲がありません。', 'minano-nihongo-46'],
    ['医者', 'いしゃ', 'Y GIẢ', 'Bác sĩ', '', 'minano-nihongo-1'],
    ['歯医者', 'はいしゃ', 'XỈ Y GIẢ', 'Nha sĩ', '', 'minano-nihongo-15'],
    ['先生', 'せんせい', 'TIÊN SINH', 'Bác sĩ', '', 'minano-nihongo-17'],
    ['病院', 'びょういん', 'BỆNH VIỆN', 'Bệnh viện', '', 'minano-nihongo-1'],
    ['入院します', 'にゅういんします', 'NHẬP VIỆN', 'nhập viện', '父が病気で入院しました。', 'minano-nihongo-38'],
    ['退院します', 'たいいんします', 'THOÁI VIỆN', 'xuất viện', '来週退院できます。', 'minano-nihongo-38'],
    ['注射', 'ちゅうしゃ', 'CHÚ XẠ', 'tiêm', '病院で注射をしてもらいました。', 'minano-nihongo-46'],
    ['救急車', 'きゅうきゅうしゃ', 'CỨU CẤP XA', 'xe cấp cứu', 'すぐに救急車を呼んでください。', 'minano-nihongo-47'],
    ['健康', 'けんこう', 'KIỆN KHANG', 'sức khỏe/ khỏe mạnh', '健康に気をつけてください。', 'minano-nihongo-32'],
    ['健康保険証', 'けんこうほけんしょう', 'KIỆN KHANG BẢO HIỂM CHỨNG', 'Thẻ bảo hiểm y tế', '', 'minano-nihongo-17'],
    ['元気', 'げんき', 'NGUYÊN KHÍ', 'khỏe', '', 'minano-nihongo-8'],
    ['調子', 'ちょうし', 'ĐIỀU TỬ', 'Tình trạng, trạng thái', '', 'minano-nihongo-19'],
    ['調子がいい', 'ちょうしがいい', 'ĐIỀU TỬ', 'Trong tình trạng tốt', '', 'minano-nihongo-19'],
    ['調子がわるい', 'ちょうしがわるい', 'ĐIỀU TỬ', 'Trong tình trạng xấu', '', 'minano-nihongo-19'],
    ['気分がいい', 'きぶんがいい', 'KHÍ PHÂN', 'thấy khỏe/ thấy dễ chịu/ tâm trạng tốt', '今日は気分がいいです。', 'minano-nihongo-26'],
    ['気分が悪い', 'きぶんがわるい', 'KHÍ PHÂN ÁC', 'thấy khó chịu/ thấy mệt/ tâm trạng tệ', '少し気分が悪いです。', 'minano-nihongo-26'],
    ['気持ちがいい', 'きもちがいい', 'KHÍ TRÌ', 'dễ chịu/ thoải mái', '朝の空気は気持ちがいいです。', 'minano-nihongo-38'],
    ['気持ちが悪い', 'きもちがわるい', 'KHÍ TRÌ ÁC', 'khó chịu', '車に乗ると気持ちが悪くなります。', 'minano-nihongo-38'],
    ['具合', 'ぐあい', 'CỤ HỢP', 'trạng thái/ tình hình', '体の具合はどうですか。', 'minano-nihongo-46'],
    ['熱を出します', 'ねつをだします', 'NHIỆT XUẤT', 'bị sốt', '子どもが熱を出しました。', 'minano-nihongo-49'],
    ['薬を飲みます', 'くすりをのみます', 'DƯỢC ẨM', 'Uống thuốc', '', 'minano-nihongo-17'],
    ['病気が治ります', 'びょうきがなおります', 'BỆNH KHÍ TRỊ', 'khỏi bệnh/ bệnh khỏi', '薬を飲んだら、病気が治りました。', 'minano-nihongo-32'],
    ['熱が続きます', 'ねつがつづきます', 'NHIỆT TỤC', 'sốt kéo dài/ vẫn còn sốt', '三日も熱が続いています。', 'minano-nihongo-32'],
    ['疲れます', 'つかれます', 'BÌ', 'mệt', '', 'minano-nihongo-13'],
    ['疲れる', 'つかれる', 'BÌ', 'Mệt mỏi', '', 'minano-nihongo-12'],
    ['眠い', 'ねむい', 'MIÊN', 'Buồn ngủ', '', 'minano-nihongo-19'],
    ['眠ります', 'ねむります', 'MIÊN', 'ngủ', '昨夜はよく眠れませんでした。', 'minano-nihongo-37'],
    ['目が覚めます', 'めがさめます', 'MỤC GIÁC', 'tỉnh giấc/ mở mắt', '朝6時に目が覚めました。', 'minano-nihongo-30'],
    ['歯を磨きます', 'はをみがきます', 'XỈ MA', 'đánh răng', '寝る前に歯を磨きます。', 'minano-nihongo-34'],
    ['お見舞い', 'おみまい', 'KIẾN VŨ', 'việc thăm người ốm', '入院した友達のお見舞いに行きます。', 'minano-nihongo-41'],
    ['無理', 'むり', 'VÔ LÝ', 'Không thể, quá sức', '', 'minano-nihongo-19'],
    ['無理をします', 'むりをします', 'VÔ LÝ', 'làm quá sức/ làm điều quá khả năng', '病気のときは無理をしないほうがいいです。', 'minano-nihongo-32'],
    ['働きすぎ', 'はたらきすぎ', 'ĐỘNG', 'làm việc quá sức', '働きすぎで体を壊しました。', 'minano-nihongo-32'],
    ['体にいい', 'からだにいい', 'THỂ', 'Tốt cho sức khỏe', '', 'minano-nihongo-19'],
    ['太ります', 'ふとります', 'THÁI', 'béo lên/ tăng cân', '運動しないと太りますよ。', 'minano-nihongo-36'],
    ['医学', 'いがく', 'Y HỌC', 'y học', '医学を勉強しています。', 'minano-nihongo-47'],
    ['年齢', 'ねんれい', 'NIÊN LINH', 'tuổi', '申し込みに年齢を書きます。', 'minano-nihongo-42'],
    ['平均寿命', 'へいきんじゅみょう', 'BÌNH QUÂN THỌ MỆNH', 'tuổi thọ trung bình', '日本人の平均寿命は世界一だそうです。', 'minano-nihongo-47'],
    ['長生きします', 'ながいきします', 'TRƯỜNG SINH', 'sống lâu', '祖母は長生きしました。', 'minano-nihongo-47'],
    ['死にます', 'しにます', 'TỬ', 'chết', '事故で人が死にました。', 'minano-nihongo-39'],
  ]],
  ['thien-nhien-thoi-tiet', [
    ['天気', 'てんき', 'THIÊN KHÍ', 'Thời tiết', '', 'minano-nihongo-12'],
    ['天気予報', 'てんきよほう', 'THIÊN KHÍ DỰ BÁO', 'dự báo thời tiết', '天気予報によると、明日は雨だそうです。', 'minano-nihongo-47'],
    ['雨', 'あめ', 'VŨ', 'Mưa', '', 'minano-nihongo-12'],
    ['雪', 'ゆき', 'TUYẾT', 'Tuyết', '', 'minano-nihongo-12'],
    ['曇り', 'くもり', 'ĐÀM', 'Có mây', '', 'minano-nihongo-12'],
    ['風', 'かぜ', 'PHONG', 'gió', '冷たい風が入ってきます。', 'minano-nihongo-32'],
    ['空', 'そら', 'KHÔNG', 'bầu trời/ trời', '今日の空は青くてきれいです。', 'minano-nihongo-27'],
    ['空気', 'くうき', 'KHÔNG KHÍ', 'không khí', '山の空気はきれいです。', 'minano-nihongo-44'],
    ['雨が降ります', 'あめがふります', 'VŨ GIÁNG/HÀNG', 'Rơi mưa, tuyết', '', 'minano-nihongo-14'],
    ['雨がやみます', 'あめがやみます', 'VŨ', 'tạnh mưa/ ngừng mưa', '雨がやんだら、出かけましょう。', 'minano-nihongo-32'],
    ['晴れます', 'はれます', 'TÌNH', 'nắng/ quang đãng/ trời hửng', '明日は晴れるでしょう。', 'minano-nihongo-32'],
    ['曇ります', 'くもります', 'ĐÀM', 'có mây/ trời râm', '午後から曇るかもしれません。', 'minano-nihongo-32'],
    ['風が吹きます', 'かぜがふきます', 'PHONG XÚY', 'gió thổi', '強い風が吹いています。', 'minano-nihongo-32'],
    ['季節', 'きせつ', 'QUÝ TIẾT', 'Mùa', '', 'minano-nihongo-12'],
    ['春', 'はる', 'XUÂN', 'Mùa xuân', '', 'minano-nihongo-12'],
    ['夏', 'なつ', 'HẠ', 'Mùa hè', '', 'minano-nihongo-12'],
    ['秋', 'あき', 'THU', 'Mùa thu', '', 'minano-nihongo-12'],
    ['冬', 'ふゆ', 'ĐÔNG', 'Mùa đông', '', 'minano-nihongo-12'],
    ['紅葉', 'もみじ', 'HỒNG DIỆP', 'Lá đỏ', '', 'minano-nihongo-12'],
    ['太陽', 'たいよう', 'THÁI DƯƠNG', 'mặt trời', '太陽が出てきました。', 'minano-nihongo-32'],
    ['月', 'つき', 'NGUYỆT', 'mặt trăng/ trăng', '今夜は月がきれいです。', 'minano-nihongo-30'],
    ['星', 'ほし', 'TINH', 'sao/ ngôi sao', '今夜は星がよく見えます。', 'minano-nihongo-32'],
    ['地球', 'ちきゅう', 'ĐỊA CẦU', 'trái đất', '地球を守りましょう。', 'minano-nihongo-30'],
    ['宇宙', 'うちゅう', 'VŨ TRỤ', 'vũ trụ', '宇宙に行ってみたいです。', 'minano-nihongo-26'],
    ['宇宙船', 'うちゅうせん', 'VŨ TRỤ THUYỀN', 'tàu vũ trụ', '宇宙船が発射します。', 'minano-nihongo-26'],
    ['自然', 'しぜん', 'TỰ NHIÊN', 'tự nhiên/ thiên nhiên', '自然が豊かな所です。', 'minano-nihongo-50'],
    ['山', 'やま', 'SƠN/ SAN', 'núi', '', 'minano-nihongo-8'],
    ['川', 'かわ', 'XUYÊN', 'sông', '', 'minano-nihongo-13'],
    ['海', 'うみ', 'HẢI', 'Biển, đại dương', '', 'minano-nihongo-12'],
    ['海岸', 'かいがん', 'HẢI NGẠN', 'bờ biển', '海岸を散歩するのが好きです。', 'minano-nihongo-38'],
    ['島', 'しま', 'ĐẢO', 'đảo/ hòn đảo', '船で島へ行きます。', 'minano-nihongo-35'],
    ['港', 'みなと', 'CẢNG', 'cảng/ bến cảng', '港に大きい船が入りました。', 'minano-nihongo-35'],
    ['池', 'いけ', 'TRÌ', 'cái ao', '池に魚がいます。', 'minano-nihongo-30'],
    ['陸', 'りく', 'LỤC', 'đất liền/ lục địa', '船が陸に着きました。', 'minano-nihongo-41'],
    ['波', 'なみ', 'BA', 'sóng', '海で高い波があります。', 'minano-nihongo-27'],
    ['景色', 'けしき', 'CẢNH SẮC', 'phong cảnh/ cảnh sắc', 'この辺の景色はきれいです。', 'minano-nihongo-27'],
    ['山に登ります', 'やまにのぼります', 'SƠN ĐĂNG', 'Leo núi', '', 'minano-nihongo-19'],
    ['山登り', 'やまのぼり', 'SƠN ĐĂNG', 'leo núi', '天気がよければ、山登りに行きます。', 'minano-nihongo-35'],
    ['花火', 'はなび', 'HOA HỎA', 'pháo hoa', '夜、花火を見に行きます。', 'minano-nihongo-27'],
    ['土地', 'とち', 'THỔ ĐỊA', 'đất/ diện tích đất', 'この辺の土地は高いです。', 'minano-nihongo-37'],
    ['田舎', 'いなか', 'ĐIỀN XÁ', 'quê, nông thôn', '', 'minano-nihongo-25'],
    ['郊外', 'こうがい', 'GIAO NGOẠI', 'ngoại ô', '郊外に住んでいます。', 'minano-nihongo-50'],
    ['世界', 'せかい', 'THẾ GIỚI', 'Thế giới', '', 'minano-nihongo-12'],
    ['世界中', 'せかいじゅう', 'THẾ GIỚI TRUNG', 'khắp thế giới/ toàn thế giới', 'この歌は世界中で歌われています。', 'minano-nihongo-37'],
    ['地震', 'じしん', 'ĐỊA CHẤN', 'động đất', 'ゆうべ大きな地震がありました。', 'minano-nihongo-29'],
    ['台風', 'たいふう', 'ĐÀI PHONG', 'bão', '台風が来て、旅行に行けませんでした。', 'minano-nihongo-39'],
    ['火事', 'かじ', 'HỎA SỰ', 'hỏa hoạn/ cháy', '火事でビルが焼けました。', 'minano-nihongo-39'],
    ['火', 'ひ', 'HỎA', 'lửa', '火に気をつけてください。', 'minano-nihongo-34'],
    ['煙', 'けむり', 'YÊN', 'khói', '工場から煙が出ています。', 'minano-nihongo-41'],
  ]],
  ['dong-vat-thuc-vat', [
    ['動物', 'どうぶつ', 'ĐỘNG VẬT', 'Động vật', '', 'minano-nihongo-18'],
    ['動物園', 'どうぶつえん', 'ĐỘNG VẬT VIÊN', 'vườn thú/ vườn bách thú', '子どもと動物園へ行きました。', 'minano-nihongo-31'],
    ['牧場', 'ぼくじょう', 'MỤC TRƯỜNG', 'Trang trại chăn nuôi', '', 'minano-nihongo-18'],
    ['犬', 'いぬ', 'KHUYỂN', 'chó', '', 'minano-nihongo-10'],
    ['猫', 'ねこ', 'MIÊU', 'Mèo', '', 'minano-nihongo-10'],
    ['馬', 'うま', 'MÃ', 'Ngựa', '', 'minano-nihongo-18'],
    ['鳥', 'とり', 'ĐIỂU', 'chim', '空に鳥が飛んでいます。', 'minano-nihongo-27'],
    ['魚', 'さかな', 'NGƯ', 'cá', '', 'minano-nihongo-6'],
    ['猿', 'さる', 'VIÊN', 'con khỉ', '山で猿を見ました。', 'minano-nihongo-41'],
    ['飼います', 'かいます', 'TỰ', 'nuôi', '猫を飼います。', 'minano-nihongo-27'],
    ['犬を飼う', 'いぬをかう', '', 'nuôi chó (keep a dog)', '', 'soumatome-n3-6'],
    ['犬にえさをやる', 'いぬにえさをやる', '', 'cho chó ăn (feed a dog)', '', 'soumatome-n3-6'],
    ['犬にえさを与える', 'いぬにえさをあたえる', '', 'cho chó ăn (feed a dog)', '', 'soumatome-n3-6'],
    ['散歩に連れていく', 'さんぽにつれていく', '', 'dắt đi dạo (take out for a walk)', '', 'soumatome-n3-6'],
    ['ほえる', '', '', 'sủa (bark)', '', 'soumatome-n3-6'],
    ['しっぽを振る', 'しっぽをふる', '', 'vẫy đuôi (wag its tail)', '', 'soumatome-n3-6'],
    ['人になれる', 'ひとになれる', '', 'quen người (become tame)', '', 'soumatome-n3-6'],
    ['うなる', '', '', 'gầm gừ (growl)', '', 'soumatome-n3-6'],
    ['穴をほる', 'あなをほる', '', 'đào hố (dig a whole)', '', 'soumatome-n3-6'],
    ['穴をうめる', 'あなをうめる', '', 'lấp hố (fill a whole)', '', 'soumatome-n3-6'],
    ['木', 'き', 'MỘC', 'cây, gỗ', '', 'minano-nihongo-10'],
    ['花', 'はな', 'HOA', 'hoa', '', 'minano-nihongo-7'],
    ['桜', 'さくら', 'ANH', 'anh đào', '', 'minano-nihongo-8'],
    ['葉', 'は', 'DIỆP', 'cái lá', '木の葉が赤くなりました。', 'minano-nihongo-35'],
    ['枝', 'えだ', 'CHI', 'cành cây', '木の枝が折れそうです。', 'minano-nihongo-29'],
    ['花が咲きます', 'はながさきます', 'HOA TIẾU', 'hoa nở', '春になると、桜の花が咲きます。', 'minano-nihongo-35'],
    ['植えます', 'うえます', 'THỰC', 'trồng cây', '庭に木を植えます。', 'minano-nihongo-30'],
    ['育てます', 'そだてます', 'DỤC', 'nuôi/ trồng', '庭で野菜を育てています。', 'minano-nihongo-38'],
    ['生け花', 'いけばな', 'SINH HOA', 'Nghệ thuật cắm hoa', '', 'minano-nihongo-12'],
    ['花瓶', 'かびん', 'HOA BÌNH', 'lọ hoa', '花瓶に花を挿します。', 'minano-nihongo-30'],
    ['米', 'こめ', 'MỄ', 'gạo', '日本では米がたくさん作られます。', 'minano-nihongo-37'],
    ['麦', 'むぎ', 'MẠCH', 'lúa mạch', '麦からビールが作られます。', 'minano-nihongo-37'],
    ['野菜', 'やさい', 'DÃ THÁI', 'rau', '', 'minano-nihongo-6'],
    ['果物', 'くだもの', 'QUẢ VẬT', 'hoa quả, trái cây', '', 'minano-nihongo-6'],
  ]],
  ['nha-cua-do-dung', [
    ['家', 'いえ', 'GIA', 'nhà', '新しい家を建てます。', 'minano-nihongo-27'],
    ['部屋', 'へや', 'BỘ ÓC', 'căn phòng', '', 'minano-nihongo-3'],
    ['台所', 'だいどころ', 'ĐÀI SỞ', 'bếp/ nhà bếp', '台所で料理を作ります。', 'minano-nihongo-27'],
    ['キッチン', '', '', 'bếp (Kitchen)', '', 'soumatome-n3-1'],
    ['リビング', '', '', 'phòng khách (Living Room)', '', 'soumatome-n3-1'],
    ['居間', 'いま', '', 'phòng khách (Living Room)', '', 'soumatome-n3-1'],
    ['和室', 'わしつ', 'HÒA THẤT', 'Phòng kiểu Nhật', '', 'minano-nihongo-22'],
    ['玄関', 'げんかん', 'HUYỀN QUAN', 'cửa vào', '玄関で靴を脱ぎます。', 'minano-nihongo-30'],
    ['廊下', 'ろうか', 'LANG HẠ', 'hành lang', '廊下を走ってはいけません。', 'minano-nihongo-30'],
    ['壁', 'かべ', 'BÍCH', 'bức tường', '壁に絵を掛けます。', 'minano-nihongo-29'],
    ['天井', 'てんじょう', '', 'trần nhà (ceiling)', '', 'soumatome-n3-1'],
    ['床', 'ゆか', '', 'sàn nhà (floor)', '', 'soumatome-n3-1'],
    ['窓', 'まど', 'SONG', 'cửa sổ', '', 'minano-nihongo-10'],
    ['窓ガラス', 'まどガラス', '', 'kính cửa sổ (window glass)', '', 'soumatome-n3-1'],
    ['雨戸', 'あまど', '', 'cửa chống mưa bão (shutter)', '', 'soumatome-n3-1'],
    ['網戸', 'あみど', '', 'cửa lưới chống côn trùng (screen)', '', 'soumatome-n3-1'],
    ['押入れ', 'おしいれ', 'ÁP NHẬP', 'Chỗ để chăn gối', '', 'minano-nihongo-22'],
    ['引き出し', 'ひきだし', 'DẪN XUẤT', 'ngăn kéo', '引き出しに鍵を入れます。', 'minano-nihongo-30'],
    ['棚', 'たな', 'BẰNG', 'giá sách', '', 'minano-nihongo-10'],
    ['本棚', 'ほんだな', 'BỔN BẰNG', 'giá sách/ kệ sách', '本棚に本を並べます。', 'minano-nihongo-27'],
    ['家具', 'かぐ', 'GIA CỤ', 'gia cụ/ đồ dùng nội thất', '新しい家具を買いました。', 'minano-nihongo-34'],
    ['机', 'つくえ', 'KỶ', 'Bàn', '', 'minano-nihongo-2'],
    ['布団', 'ふとん', 'BỐ ĐOÀN', 'Chăn, đệm', '', 'minano-nihongo-22'],
    ['じゅうたん', '', '', 'thảm (carpet)', '', 'soumatome-n3-1'],
    ['カーペット', '', '', 'thảm (carpet)', '', 'soumatome-n3-1'],
    ['鏡', 'かがみ', 'KÍNH', 'cái gương', '鏡で顔を見ます。', 'minano-nihongo-30'],
    ['花瓶', 'かびん', 'HOA BÌNH', 'lọ hoa', '花瓶に花を挿します。', 'minano-nihongo-30'],
    ['人形', 'にんぎょう', 'NHÂN HÌNH', 'con búp bê/ con rối', '可愛い人形を買いました。', 'minano-nihongo-30'],
    ['ごみ箱', 'ごみばこ', 'TƯƠNG', 'thùng rác', 'ごみをごみ箱に捨てます。', 'minano-nihongo-30'],
    ['灰皿', 'はいざら', 'HỘI MÃNH', 'cái gạt tàn', '灰皿はどこにありますか。', 'minano-nihongo-49'],
    ['道具', 'どうぐ', 'ĐẠO CỤ', 'dụng cụ/ công cụ', '料理の道具を買います。', 'minano-nihongo-27'],
    ['冷蔵庫', 'れいぞうこ', 'LÃNH TÀNG KHỐ', 'tủ lạnh', '', 'minano-nihongo-10'],
    ['洗濯機', 'せんたくき', 'TẨY TRẠC CƠ', 'máy giặt', '洗濯機が壊れてしまいました。', 'minano-nihongo-33'],
    ['電子レンジ', 'でんしレンジ', '', 'lò vi sóng (microwave)', '', 'soumatome-n3-1'],
    ['ガスレンジ', '', '', 'bếp ga (gas stove)', '', 'soumatome-n3-1'],
    ['ガスコンロ', '', '', 'bếp ga (gas stove)', '', 'soumatome-n3-1'],
    ['炊飯器', 'すいはんき', '', 'nồi cơm điện (rice cooker)', '', 'soumatome-n3-3'],
    ['流し', 'ながし', '', 'bồn rửa (sink)', '', 'soumatome-n3-1'],
    ['エアコン', '', '', 'điều hoà (air conditioner)', '', 'soumatome-n3-1'],
    ['ヒーター', '', '', 'lò sưởi (heater)', '', 'soumatome-n3-1'],
    ['暖房', 'だんぼう', 'NOÃN PHÒNG', 'lò sưởi/ thiết bị làm ấm', '暖房のために電気をたくさん使います。', 'minano-nihongo-42'],
    ['冷房', 'れいぼう', 'LÃNH PHÒNG', 'máy lạnh/ thiết bị làm mát', '夏は冷房が必要です。', 'minano-nihongo-42'],
    ['コンセント', '', '', 'ổ cắm điện (electrical outlet)', '', 'soumatome-n3-1'],
    ['コード', '', '', 'dây điện (cord)', '', 'soumatome-n3-1'],
    ['スイッチ', '', '', 'công tắc (switch)', '', 'soumatome-n3-1'],
    ['電源', 'でんげん', 'ĐIỆN NGUYÊN', 'nguồn điện/ công tắc điện', '電源はここにあります。', 'minano-nihongo-38'],
    ['電池', 'でんち', 'ĐIỆN TRÌ', 'Pin', '', 'minano-nihongo-10'],
    ['電気', 'でんき', 'ĐIỆN KHÍ', 'Điện, Đèn điện', '', 'minano-nihongo-1'],
    ['水道', 'すいどう', 'THỦY ĐẠO', 'nước máy', '水道の水が出ません。', 'minano-nihongo-32'],
    ['箱', 'はこ', 'TƯƠNG', 'hộp', '', 'minano-nihongo-10'],
    ['袋', 'ふくろ', 'ĐẠI', 'cái túi', 'パンを袋に入れます。', 'minano-nihongo-29'],
    ['お皿', 'おさら', 'MÃNH', 'cái đĩa', 'お皿を洗います。', 'minano-nihongo-29'],
    ['庭', 'にわ', 'ĐÌNH', 'vườn', '', 'minano-nihongo-6'],
    ['屋上', 'おくじょう', 'ỐC THƯỢNG', 'sân thượng/ nóc nhà', '屋上から町が見えます。', 'minano-nihongo-35'],
    ['家賃', 'やちん', 'GIA NHẦM', 'Tiền thuê nhà', '', 'minano-nihongo-22'],
    ['引っ越しします', 'ひっこしします', 'DẪN VIỆT', 'Chuyển nhà', '', 'minano-nihongo-23'],
    ['建てます', 'たてます', 'KIẾN', 'xây/ xây dựng', '家を建てます。', 'minano-nihongo-27'],
    ['掃除します', 'そうじします', 'TẢO TRÚ', 'Dọn vệ sinh', '', 'minano-nihongo-19'],
    ['片づけます', 'かたづけます', 'PHIẾN', 'dọn dẹp/ sắp xếp', '部屋を片づけます。', 'minano-nihongo-30'],
    ['物置にしまう', 'ものおきにしまう', '', 'cất vào nhà kho (put it away in the storage)', '', 'soumatome-n3-4'],
  ]],
  ['an-uong-nau-an', [
    ['食べ物', 'たべもの', 'THỰC VẬT', 'đồ ăn', '', 'minano-nihongo-8'],
    ['飲み物', 'のみもの', 'ẨM VẬT', 'đồ uống', '', 'minano-nihongo-9'],
    ['料理', 'りょうり', 'LIỆU LÝ', 'món ăn, việc nấu ăn', '', 'minano-nihongo-9'],
    ['食事します', 'しょくじします', 'THỰC SỰ', 'ăn cơm', '', 'minano-nihongo-13'],
    ['食欲', 'しょくよく', 'THỰC DỤC', 'sự thèm ăn/ cảm giác muốn ăn', '暑くて食欲がありません。', 'minano-nihongo-46'],
    ['朝ごはん', 'あさごはん', 'TRIỀU', 'cơm sáng', '', 'minano-nihongo-6'],
    ['昼ごはん', 'ひるごはん', 'TRÚ', 'cơm trưa', '', 'minano-nihongo-6'],
    ['晩ごはん', 'ばんごはん', 'VÃN', 'cơm tối', '', 'minano-nihongo-6'],
    ['お弁当', 'おべんとう', 'BIỆN ĐƯƠNG', 'Cơm hộp', '', 'minano-nihongo-24'],
    ['お菓子', 'おかし', 'QUẢ TỬ', 'Bánh kẹo', '', 'minano-nihongo-24'],
    ['和食', 'わしょく', 'HÒA THỰC', 'món ăn Nhật', '和食が好きになりました。', 'minano-nihongo-44'],
    ['洋食', 'ようしょく', 'DƯƠNG THỰC', 'món ăn Âu Mỹ', '今日は洋食にしましょう。', 'minano-nihongo-44'],
    ['すき焼き', 'すきやき', 'THIÊU', 'Món sukiyaki', '', 'minano-nihongo-12'],
    ['刺身', 'さしみ', 'THÍCH THÂN', 'Món sashimi', '', 'minano-nihongo-12'],
    ['肉じゃが', 'にくじゃが', '', 'món thịt hầm khoai tây', '', 'soumatome-n3-2'],
    ['卵', 'たまご', 'NOÃN', 'trứng', '', 'minano-nihongo-6'],
    ['肉', 'にく', 'NHỤC', 'thịt', '', 'minano-nihongo-6'],
    ['牛肉', 'ぎゅうにく', '', 'thịt bò', '', 'soumatome-n3-2'],
    ['鳥肉', 'とりにく', 'ĐIỂU', 'thịt gà', '鳥肉を小さく切ります。', 'minano-nihongo-34'],
    ['魚', 'さかな', 'NGƯ', 'cá', '', 'minano-nihongo-6'],
    ['野菜', 'やさい', 'DÃ THÁI', 'rau', '', 'minano-nihongo-6'],
    ['果物', 'くだもの', 'QUẢ VẬT', 'hoa quả, trái cây', '', 'minano-nihongo-6'],
    ['米', 'こめ', 'MỄ', 'gạo', '日本では米がたくさん作られます。', 'minano-nihongo-37'],
    ['麦', 'むぎ', 'MẠCH', 'lúa mạch', '麦からビールが作られます。', 'minano-nihongo-37'],
    ['ジャガイモ', '', '', 'khoai tây', '', 'soumatome-n3-2'],
    ['玉ネギ', 'たまネギ', '', 'hành tây', '', 'soumatome-n3-2'],
    ['水', 'みず', 'THỦY', 'nước', '', 'minano-nihongo-6'],
    ['お湯', 'おゆ', 'THANG', 'nước nóng/ nước sôi', 'お湯を沸かします。', 'minano-nihongo-26'],
    ['お茶', 'おちゃ', 'TRÀ', 'trà', '', 'minano-nihongo-6'],
    ['紅茶', 'こうちゃ', 'HỒNG TRÀ', 'trà đen', '', 'minano-nihongo-6'],
    ['牛乳', 'ぎゅうにゅう', 'NGƯU NHŨ', 'sữa bò', '', 'minano-nihongo-6'],
    ['お酒', 'おさけ', 'TỬU', 'rượu, rượu sake', '', 'minano-nihongo-6'],
    ['酒', 'さけ', '', 'rượu (rice wine)', '', 'soumatome-n3-2'],
    ['乾杯', 'かんぱい', 'CAN BỘI', 'Nâng cốc!/cạn chén', '', 'minano-nihongo-19'],
    ['材料', 'ざいりょう', 'TÀI LIỆU', 'nguyên liệu', '料理の材料を買いに行きます。', 'minano-nihongo-34'],
    ['調味料', 'ちょうみりょう', 'ĐIỀU VỊ LIỆU', 'gia vị', '調味料を入れてよく混ぜます。', 'minano-nihongo-34'],
    ['塩', 'しお', 'DIÊM', 'Muối', '', 'minano-nihongo-14'],
    ['砂糖', 'さとう', 'SA ĐƯỜNG', 'Đường', '', 'minano-nihongo-14'],
    ['しょうゆ', '', '', 'nước tương/ xì dầu', '', 'soumatome-n3-2'],
    ['酢', 'す', '', 'giấm (vinegar)', '', 'soumatome-n3-2'],
    ['サラダ油', 'サラダあぶら', '', 'dầu ăn (salad oil)', '', 'soumatome-n3-2'],
    ['味', 'あじ', 'VỊ', 'vị/ mùi vị', 'このスープは良い味です。', 'minano-nihongo-28'],
    ['味がします', 'あじがします', 'VỊ', 'có vị', '甘い味がします。', 'minano-nihongo-47'],
    ['味が濃い', 'あじがこい', '', 'đậm vị (it has a strong flavor)', '', 'soumatome-n3-3'],
    ['味が薄い', 'あじがうすい', '', 'nhạt vị (it has a weak flavor)', '', 'soumatome-n3-3'],
    ['味見をする', 'あじみをする', '', 'nếm thử (taste)', '', 'soumatome-n3-3'],
    ['味を見る', 'あじをみる', '', 'nếm thử (taste)', '', 'soumatome-n3-3'],
    ['甘い', 'あまい', 'CAM', 'Ngọt', '', 'minano-nihongo-12'],
    ['辛い', 'からい', 'TÂN', 'Cay', '', 'minano-nihongo-12'],
    ['からい', '', '', 'cay/ mặn (spicy, hot, salty)', '', 'soumatome-n3-3'],
    ['塩からい', 'しおからい', '', 'mặn (salty)', '', 'soumatome-n3-3'],
    ['すっぱい', '', '', 'chua (sour)', '', 'soumatome-n3-3'],
    ['苦い', 'にがい', 'KHỔ', 'đắng', 'この薬は苦いです。', 'minano-nihongo-34'],
    ['濃い', 'こい', 'NỒNG', 'đậm/ nồng', 'コーヒーが濃すぎます。', 'minano-nihongo-44'],
    ['薄い', 'うすい', 'BẠC', 'nhạt/ mỏng', '味が薄いですね。', 'minano-nihongo-44'],
    ['煮ます', 'にます', 'CHỬ', 'nấu/ hầm', '野菜を弱火で煮ます。', 'minano-nihongo-34'],
    ['煮えます', 'にえます', 'CHỬ', 'chín/ được nấu chín', '野菜が煮えたら、火を止めてください。', 'minano-nihongo-34'],
    ['焼きます', 'やきます', 'THIÊU', 'nướng/ rán', '魚を焼いているところです。', 'minano-nihongo-46'],
    ['焼けます', 'やけます', 'THIÊU', 'cháy/ chín (nướng)', '火事で家が焼けてしまいました。', 'minano-nihongo-39'],
    ['ゆでる', '', '', 'luộc (boil)', '', 'soumatome-n3-3'],
    ['いためる', '', '', 'xào (stir fry)', '', 'soumatome-n3-3'],
    ['蒸す', 'むす', '', 'hấp (steam)', '', 'soumatome-n3-3'],
    ['混ぜる', 'まぜる', '', 'trộn (mix)', '', 'soumatome-n3-3'],
    ['ご飯を炊く', 'ごはんをたく', '', 'nấu cơm (cook rice)', '', 'soumatome-n3-3'],
    ['油で揚げる', 'あぶらであげる', '', 'chiên ngập dầu (deep fry)', '', 'soumatome-n3-3'],
    ['皮をむく', 'かわをむく', '', 'gọt vỏ (peel)', '', 'soumatome-n3-2'],
    ['なべ', '', '', 'nồi (pot/pan)', '', 'soumatome-n3-3'],
    ['フライパン', '', '', 'chảo (frying pan)', '', 'soumatome-n3-3'],
    ['包丁', 'ほうちょう', '', 'dao làm bếp (kitchen knife)', '', 'soumatome-n3-2'],
    ['まな板', 'まないた', '', 'thớt (cutting board)', '', 'soumatome-n3-2'],
    ['大さじ', 'おおさじ', '', 'thìa canh (table spoon)', '', 'soumatome-n3-2'],
    ['小さじ', 'こさじ', '', 'thìa cà phê (tea spoon)', '', 'soumatome-n3-2'],
  ]],
  ['quan-ao-do-dung', [
    ['服', 'ふく', 'PHỤC', 'Quần áo', '', 'minano-nihongo-15'],
    ['洋服', 'ようふく', 'DƯƠNG PHỤC', 'quần áo kiểu Tây Âu', '洋服を着て出かけます。', 'minano-nihongo-39'],
    ['着物', 'きもの', 'TRƯỚC VẬT', 'Kimono', '', 'minano-nihongo-20'],
    ['上着', 'うわぎ', 'THƯỢNG TRƯỚC', 'Áo khoác', '', 'minano-nihongo-17'],
    ['下着', 'したぎ', 'HẠ TRƯỚC', 'Quần áo lót', '', 'minano-nihongo-17'],
    ['エプロン', '', '', 'tạp dề (apron)', '', 'soumatome-n3-4'],
    ['シャツを着ます', 'シャツをきます', 'TRƯỚC', 'Mặc áo sơ mi', '', 'minano-nihongo-22'],
    ['靴', 'くつ', 'NGOA', 'giầy', '', 'minano-nihongo-3'],
    ['靴をはきます', 'くつをはきます', 'NGOA', 'mang giầy', '', 'minano-nihongo-22'],
    ['靴下', 'くつした', 'NGOA HẠ', 'cái tất', '靴下を買いました。', 'minano-nihongo-41'],
    ['帽子', 'ぼうし', 'MẠO TỬ', 'Mũ', '', 'minano-nihongo-22'],
    ['帽子をかぶります', 'ぼうしをかぶります', 'MẠO TỬ', 'Đội mũ', '', 'minano-nihongo-22'],
    ['眼鏡', 'めがね', 'NHÃN KÍNH', 'Kính', '', 'minano-nihongo-22'],
    ['眼鏡をかけます', 'めがねをかけます', 'NHÃN KÍNH', 'Đeo kính', '', 'minano-nihongo-22'],
    ['手袋', 'てぶくろ', 'THỦ ĐẠI', 'cái găng tay', '母に手袋をいただきました。', 'minano-nihongo-41'],
    ['指輪', 'ゆびわ', 'CHỈ LUÂN', 'cái nhẫn', '妻に指輪をあげました。', 'minano-nihongo-41'],
    ['財布', 'さいふ', 'TÀI BỐ', 'cái ví', '財布をなくしました。', 'minano-nihongo-29'],
    ['傘', 'かさ', 'TẢN', 'ô, dù', '', 'minano-nihongo-2'],
    ['傘をさします', 'かさをさします', 'TẢN', 'che ô', '雨が降ってきたので、傘をさしました。', 'minano-nihongo-47'],
    ['時計', 'とけい', 'THỜI KẾ', 'Đồng hồ', '', 'minano-nihongo-2'],
    ['目覚まし時計', 'めざましどけい', 'MỤC GIÁC THỜI KẾ', 'đồng hồ báo thức', '目覚まし時計が鳴りませんでした。', 'minano-nihongo-45'],
    ['荷物', 'にもつ', 'HÀ VẬT', 'đồ đạc, hành lý', '', 'minano-nihongo-7'],
    ['名刺', 'めいし', 'DANH THÍCH', 'Danh thiếp', '', 'minano-nihongo-2'],
    ['手帳', 'てちょう', 'THỦ TRƯƠNG', 'Sổ tay', '', 'minano-nihongo-2'],
    ['鏡', 'かがみ', 'KÍNH', 'cái gương', '鏡で顔を見ます。', 'minano-nihongo-30'],
    ['化粧', 'けしょう', 'HÓA TRANG', 'sự trang điểm', '姉は化粧をしているところです。', 'minano-nihongo-47'],
    ['化粧品', 'けしょうひん', 'HÓA TRANG PHẨM', 'mỹ phẩm', 'デパートで化粧品を買いました。', 'minano-nihongo-47'],
    ['サイズが合います', 'サイズがあいます', 'HỢP', 'vừa kích thước/ hợp cỡ', 'サイズが合うかどうか着てみます。', 'minano-nihongo-40'],
    ['合います', 'あいます', 'HỢP', 'vừa/ hợp', 'この靴は足に合いません。', 'minano-nihongo-39'],
    ['ボタンが外れます', 'ボタンがはずれます', 'NGOẠI', 'cúc bị tuột', 'シャツのボタンが外れました。', 'minano-nihongo-29'],
    ['ボタンがとれます', '', 'THỦ', 'cái cúc bị tuột', 'シャツのボタンがとれました。', 'minano-nihongo-42'],
    ['洗濯物', 'せんたくもの', 'TẨY TRẠC VẬT', 'quần áo giặt', '洗濯物がまだ乾きません。', 'minano-nihongo-44'],
    ['洗濯します', 'せんたくします', 'TẨY TRẠC', 'Giặt', '', 'minano-nihongo-19'],
    ['干す', 'ほす', '', 'phơi (put it out for drying)', '', 'soumatome-n3-5'],
    ['たたむ', '', '', 'gấp (fold)', '', 'soumatome-n3-5'],
    ['汚れ', 'よごれ', '', 'vết bẩn (dirt)', '', 'soumatome-n3-5'],
    ['汚します', 'よごします', 'Ô', 'làm bẩn', '子どもに服を汚されました。', 'minano-nihongo-37'],
    ['服を汚す', 'ふくをよごす', '', "làm bẩn quần áo (get one's clothes dirty)", '', 'soumatome-n3-5'],
  ]],
  ['phuong-huong-vi-tri', [
    ['上', 'うえ', 'THƯỢNG', 'Trên', '', 'minano-nihongo-10'],
    ['下', 'した', 'HẠ', 'dưới', '', 'minano-nihongo-10'],
    ['前', 'まえ', 'TIỀN', 'trước', '', 'minano-nihongo-10'],
    ['右', 'みぎ', 'HỮU', 'phải', '', 'minano-nihongo-10'],
    ['左', 'ひだり', 'TẢ', 'Trái', '', 'minano-nihongo-10'],
    ['中', 'なか', 'TRUNG', 'trong, giữa', '', 'minano-nihongo-10'],
    ['外', 'そと', 'NGOẠI', 'Ngoài', '', 'minano-nihongo-10'],
    ['隣', 'となり', 'LÂN', 'bên cạnh', '', 'minano-nihongo-10'],
    ['近く', 'ちかく', 'CẬN', 'gần', '', 'minano-nihongo-10'],
    ['間', 'あいだ', 'GIAN', 'giữa', '', 'minano-nihongo-10'],
    ['奥', 'おく', 'ÁO', 'bên trong cùng, phía sâu bên trong', '', 'minano-nihongo-10'],
    ['横', 'よこ', 'HOÀNH', 'bên cạnh/ cạnh', '駅の横にスーパーがあります。', 'minano-nihongo-26'],
    ['周り', 'まわり', 'CHU', 'xung quanh', '家の周りを散歩します。', 'minano-nihongo-30'],
    ['真ん中', 'まんなか', 'CHÂN TRUNG', 'giữa/ trung tâm', 'テーブルの真ん中に花を置きます。', 'minano-nihongo-30'],
    ['隅', 'すみ', 'NGUNG', 'góc', '部屋の隅に机を置きます。', 'minano-nihongo-30'],
    ['表', 'おもて', 'BIỂU', 'mặt trước/ phía trước', '紙の表に名前を書きます。', 'minano-nihongo-40'],
    ['裏', 'うら', 'LÝ', 'mặt sau/ phía sau', '裏に住所を書いてください。', 'minano-nihongo-40'],
    ['向こう', 'むこう', 'HƯỚNG', 'bên kia/ phía đằng kia', '川の向こうに山が見えます。', 'minano-nihongo-35'],
    ['中身', 'なかみ', 'TRUNG THÂN', 'nội dung/ phần bên trong', '箱の中身は何ですか。', 'minano-nihongo-41'],
    ['東', 'ひがし', 'ĐÔNG', 'đông/ phía đông', '東の空が明るくなりました。', 'minano-nihongo-32'],
    ['西', 'にし', 'TÂY', 'tây/ phía tây', '太陽は西に沈みます。', 'minano-nihongo-29'],
    ['南', 'みなみ', 'NAM', 'nam/ phía nam', '南の島へ旅行したいです。', 'minano-nihongo-32'],
    ['北', 'きた', 'BẮC', 'bắc/ phía bắc', '北の空が暗くなりました。', 'minano-nihongo-32'],
    ['方', 'ほう', 'PHƯƠNG', 'hướng/ phương hướng', '駅はあっちの方です。', 'minano-nihongo-29'],
    ['場所', 'ばしょ', 'TRƯỜNG SỞ', 'địa điểm/ nơi/ chỗ', '約束の場所に行きます。', 'minano-nihongo-26'],
    ['所', 'ところ', 'SỞ', 'nơi, chỗ', '', 'minano-nihongo-8'],
    ['元の所', 'もとのところ', 'NGUYÊN SỞ', 'địa điểm ban đầu/ địa điểm gốc', '使ったら元の所に戻してください。', 'minano-nihongo-30'],
    ['この辺', 'このへん', 'BIÊN', 'xung quanh đây/ gần đây', 'この辺は静かです。', 'minano-nihongo-29'],
    ['遠く', 'とおく', 'VIỄN', 'xa/ ở xa', '遠くに富士山が見えます。', 'minano-nihongo-36'],
    ['近い', 'ちかい', 'CẬN', 'Gần', '', 'minano-nihongo-12'],
    ['遠い', 'とおい', 'VIỄN', 'Xa', '', 'minano-nihongo-12'],
    ['離れた', 'はなれた', 'LY', 'xa/ cách xa', '駅から離れた所に住んでいます。', 'minano-nihongo-40'],
    ['角', 'かど', 'GIÁC', 'Góc', '', 'minano-nihongo-23'],
    ['入口', 'いりぐち', 'NHẬP KHẨU', 'lối vào/ cửa vào', '入口はあちらです。', 'minano-nihongo-33'],
    ['出口', 'でぐち', 'XUẤT KHẨU', 'lối ra/ cửa ra', '出口はどこですか。', 'minano-nihongo-33'],
    ['非常口', 'ひじょうぐち', 'PHI THƯỜNG KHẨU', 'lối thoát hiểm/ cửa thoát hiểm', '地震のときは非常口から出てください。', 'minano-nihongo-33'],
    ['右へ曲がります', 'みぎへまがります', 'HỮU KHÚC', 'Rẽ, quẹo phải', '', 'minano-nihongo-14'],
    ['向かいます', 'むかいます', 'HƯỚNG', 'đi hướng đến/ trên đường đến', '今、会社に向かっているところです。', 'minano-nihongo-46'],
  ]],
  ['giao-thong-di-lai', [
    ['交通', 'こうつう', 'GIAO THÔNG', 'Giao thông, đi lại', '', 'minano-nihongo-21'],
    ['乗り物', 'のりもの', 'THỪA VẬT', 'phương tiện đi lại', 'この町は乗り物が便利です。', 'minano-nihongo-36'],
    ['電車', 'でんしゃ', 'ĐIỆN XA', 'tàu điện', '', 'minano-nihongo-5'],
    ['地下鉄', 'ちかてつ', 'ĐỊA HẠ THIẾT', 'tàu điện ngầm', '', 'minano-nihongo-5'],
    ['新幹線', 'しんかんせん', 'TÂN CAN TUYẾN', 'tàu Shinkansen', '', 'minano-nihongo-5'],
    ['汽車', 'きしゃ', 'KHÍ XA', 'tàu hỏa chạy bằng hơi nước', '昔は汽車で旅行しました。', 'minano-nihongo-36'],
    ['汽船', 'きせん', 'KHÍ THUYỀN', 'thuyền chạy bằng hơi nước', '汽船で島へ渡りました。', 'minano-nihongo-36'],
    ['船', 'ふね', 'THUYỀN', 'thuyền, tàu thủy', '', 'minano-nihongo-5'],
    ['飛行機', 'ひこうき', 'PHI HÀNH CƠ', 'máy bay', '', 'minano-nihongo-5'],
    ['自転車', 'じてんしゃ', 'TỰ CHUYỂN XA', 'xe đạp', '', 'minano-nihongo-5'],
    ['自動車', 'じどうしゃ', 'TỰ ĐỘNG XA', 'ô tô, xe hơi', '', 'minano-nihongo-2'],
    ['車', 'くるま', 'XA', 'xe ô tô', '', 'minano-nihongo-8'],
    ['歩いて', 'あるいて', 'BỘ', 'đi bộ', '', 'minano-nihongo-5'],
    ['普通', 'ふつう', 'PHỔ THÔNG', 'tàu thường (dừng cả ở các ga lẻ)', '', 'minano-nihongo-5'],
    ['急行', 'きゅうこう', 'CẤP HÀNH', 'tàu tốc hành', '', 'minano-nihongo-5'],
    ['特急', 'とっきゅう', 'ĐẶC CẤP', 'tàu tốc hành đặc biệt', '', 'minano-nihongo-5'],
    ['便', 'びん', 'TIỆN', 'chuyến bay', '何便で行きますか。', 'minano-nihongo-40'],
    ['切符', 'きっぷ', 'THIẾT PHÙ', 'vé', '', 'minano-nihongo-7'],
    ['乗り場', 'のりば', 'THỪA TRƯỜNG', 'bến xe, điểm lên xuống xe', '', 'minano-nihongo-10'],
    ['バス停', 'バスてい', 'ĐÌNH', 'điểm dừng xe buýt', 'バス停で待っています。', 'minano-nihongo-49'],
    ['駅', 'えき', 'DỊCH', 'ga, nhà ga', '', 'minano-nihongo-5'],
    ['駅員', 'えきいん', 'DỊCH VIÊN', 'nhân viên nhà ga', '駅員に道を尋ねます。', 'minano-nihongo-29'],
    ['駅前', 'えきまえ', 'DỊCH TIỀN', 'khu vực trước nhà ga', '駅前で友達と待ち合わせます。', 'minano-nihongo-29'],
    ['空港', 'くうこう', 'KHÔNG CẢNG', 'Sân bay', '', 'minano-nihongo-12'],
    ['港', 'みなと', 'CẢNG', 'cảng/ bến cảng', '港に大きい船が入りました。', 'minano-nihongo-35'],
    ['網棚', 'あみだな', 'VÕNG BẰNG', 'giá lưới/ giá để hành lý (trên tàu)', '網棚に荷物を置きます。', 'minano-nihongo-29'],
    ['忘れ物', 'わすれもの', 'VONG VẬT', 'vật để quên', '電車の中に忘れ物をしました。', 'minano-nihongo-29'],
    ['道', 'みち', 'ĐẠO', 'Đường', '', 'minano-nihongo-23'],
    ['交差点', 'こうさてん', 'GIAO SAI ĐIỂM', 'Ngã tư', '', 'minano-nihongo-23'],
    ['信号', 'しんごう', 'TÍN HIỆU', 'Đèn tín hiệu', '', 'minano-nihongo-23'],
    ['角', 'かど', 'GIÁC', 'Góc', '', 'minano-nihongo-23'],
    ['橋', 'はし', 'KIỀU', 'Cầu', '', 'minano-nihongo-23'],
    ['駐車場', 'ちゅうしゃじょう', 'TRÚ XA TRƯỜNG', 'Bãi đỗ xe', '', 'minano-nihongo-23'],
    ['地図', 'ちず', 'ĐỊA ĐỒ', 'Bản đồ', '', 'minano-nihongo-14'],
    ['運転します', 'うんてんします', 'VẬN CHUYỂN', 'Lái', '', 'minano-nihongo-18'],
    ['運転手', 'うんてんしゅ', 'VẬN CHUYỂN THỦ', 'tài xế', 'タクシーの運転手に聞いてみます。', 'minano-nihongo-40'],
    ['電車に乗ります', 'でんしゃにのります', 'ĐIỆN XA THỪA', 'Đi, lên tàu', '', 'minano-nihongo-16'],
    ['電車を降ります', 'でんしゃをおります', 'ĐIỆN XA GIÁNG/HÀNG', 'Xuống tàu', '', 'minano-nihongo-16'],
    ['乗り換えます', 'のりかえます', 'THỪA HOÁN', 'Chuyển, đổi (tàu)', '', 'minano-nihongo-16'],
    ['橋を渡ります', 'はしをわたります', 'KIỀU ĐỘ', 'Qua, đi qua cầu', '', 'minano-nihongo-23'],
    ['道を歩きます', 'みちをあるきます', 'ĐẠO BỘ', 'Đi bộ trên đường', '', 'minano-nihongo-23'],
    ['道を走ります', 'みちをはしります', 'ĐẠO TẨU', 'chạy trên đường', '車が道を走ります。', 'minano-nihongo-27'],
    ['道を通ります', 'みちをとおります', 'ĐẠO THÔNG', 'đi qua đường', 'この道を通って駅へ行きます。', 'minano-nihongo-39'],
    ['道が込みます', 'みちがこみます', 'ĐẠO VÀO', 'đường đông/ tắc đường', '朝はいつも道が込みます。', 'minano-nihongo-29'],
    ['道がすきます', 'みちがすきます', 'ĐẠO', 'đường vắng/ đường thoáng', '夜になると道がすきます。', 'minano-nihongo-29'],
    ['出発します', 'しゅっぱつします', 'XUẤT PHÁT', 'xuất phát/ khởi hành', '何時に出発するか聞いてみます。', 'minano-nihongo-40'],
    ['到着します', 'とうちゃくします', 'ĐÁO TRƯỚC', 'đến/ đến nơi', '飛行機は3時に到着します。', 'minano-nihongo-40'],
    ['遅刻します', 'ちこくします', 'TRÌ KHẮC', 'đến chậm/ đến muộn', '電車が遅れて、遅刻しました。', 'minano-nihongo-39'],
    ['時間に遅れます', 'じかんにおくれます', 'THỜI GIAN TRÌ', 'muộn giờ/ trễ giờ/ đến muộn', '会議の時間に遅れます。', 'minano-nihongo-26'],
    ['事故', 'じこ', 'SỰ CỐ', 'tai nạn/ sự cố', '事故があって、道が込んでいます。', 'minano-nihongo-39'],
    ['事故に遭います', 'じこにあいます', 'SỰ CỐ TAO', 'gặp tai nạn', '事故に遭った場合は、すぐ連絡してください。', 'minano-nihongo-45'],
    ['事故が起きます', 'じこがおきます', 'SỰ CỐ KHỞI', 'xảy ra tai nạn', '交差点で事故が起きました。', 'minano-nihongo-44'],
    ['駐車違反', 'ちゅうしゃいはん', 'TRÚ XA VI PHẢN', 'đỗ xe sai quy định/ đỗ xe trái phép', 'ここに止めると駐車違反になります。', 'minano-nihongo-33'],
    ['危ない', 'あぶない', 'NGUY', 'Nguy hiểm', '', 'minano-nihongo-17'],
    ['危険', 'きけん', 'NGUY HIỂM', 'nguy hiểm', 'ここは危険ですから、入らないでください。', 'minano-nihongo-40'],
    ['安全', 'あんぜん', 'AN TOÀN', 'an toàn', '子どもが安全に遊べる公園です。', 'minano-nihongo-44'],
  ]],
  ['du-lich-giai-tri', [
    ['旅行', 'りょこう', 'LỮ HÀNH', 'Du lịch, chuyến du lịch', '', 'minano-nihongo-7'],
    ['旅行社', 'りょこうしゃ', 'LỮ HÀNH XÃ', 'công ty du lịch', '旅行社で切符を買いました。', 'minano-nihongo-35'],
    ['旅館', 'りょかん', 'LỮ QUÁN', 'khách sạn kiểu Nhật', '旅館に泊まりました。', 'minano-nihongo-49'],
    ['お土産', 'おみやげ', 'THỔ SẢN', 'quà', '', 'minano-nihongo-7'],
    ['夜行バス', 'やこうバス', 'DẠ HÀNH', 'xe buýt chạy đêm', '夜行バスで大阪へ行きます。', 'minano-nihongo-35'],
    ['ホテルに泊まります', 'ホテルにとまります', 'BẠC', 'Trọ ở khách sạn', '', 'minano-nihongo-19'],
    ['予約します', 'よやくします', 'DỰ ƯỚC', 'Đặt chỗ, đặt trước', '', 'minano-nihongo-18'],
    ['案内します', 'あんないします', 'ÁN NỘI', 'Hướng dẫn, giới thiệu', '', 'minano-nihongo-24'],
    ['案内書', 'あんないしょ', 'ÁN NỘI THƯ', 'sách hướng dẫn/ tài liệu hướng dẫn', '旅行の案内書を読みます。', 'minano-nihongo-30'],
    ['見学します', 'けんがくします', 'KIẾN HỌC', 'Thăm quan với mục đích học tập', '', 'minano-nihongo-18'],
    ['海外', 'かいがい', 'HẢI NGOẠI', 'nước ngoài/ hải ngoại', '海外へ旅行したいです。', 'minano-nihongo-35'],
    ['外国', 'がいこく', 'NGOẠI QUỐC', 'nước ngoài', '', 'minano-nihongo-11'],
    ['写真', 'しゃしん', 'TẢ CHÂN', 'ảnh', '', 'minano-nihongo-6'],
    ['スキー場', 'スキーじょう', 'TRƯỜNG', 'bãi trượt tuyết', '冬はスキー場が込みます。', 'minano-nihongo-35'],
    ['山登り', 'やまのぼり', 'SƠN ĐĂNG', 'leo núi', '天気がよければ、山登りに行きます。', 'minano-nihongo-35'],
    ['休み', 'やすみ', 'HƯU', 'Nghỉ, nghỉ phép, ngày nghỉ', '', 'minano-nihongo-4'],
    ['休みを取ります', 'やすみをとります', 'HƯU THỦ', 'xin nghỉ/ nghỉ phép', '明日休みを取ります。', 'minano-nihongo-27'],
    ['連休', 'れんきゅう', 'LIÊN HƯU', 'ngày nghỉ liền nhau/ kỳ nghỉ dài', '連休に旅行しようと思っています。', 'minano-nihongo-31'],
    ['週末', 'しゅうまつ', 'CHU MẠT', 'cuối tuần', '', 'minano-nihongo-13'],
    ['お祭り', 'おまつり', 'TẾ', 'Lễ hội', '', 'minano-nihongo-12'],
    ['花火', 'はなび', 'HOA HỎA', 'pháo hoa', '夜、花火を見に行きます。', 'minano-nihongo-27'],
    ['展覧会', 'てんらんかい', 'TRIỂN LÃM HỘI', 'triển lãm', '美術館で展覧会を見ました。', 'minano-nihongo-31'],
    ['会場', 'かいじょう', 'HỘI TRƯỜNG', 'hội trường', '会場はあちらです。', 'minano-nihongo-49'],
    ['大会', 'たいかい', 'ĐẠI HỘI', 'đại hội/ cuộc thi', 'マラソン大会に出ました。', 'minano-nihongo-40'],
    ['試合', 'しあい', 'THỨC HỢP', 'Trận đấu', '', 'minano-nihongo-21'],
    ['趣味', 'しゅみ', 'THÚ VỊ', 'Sở thích, thú vui', '', 'minano-nihongo-18'],
    ['楽しみ', 'たのしみ', 'NHẠC', 'niềm vui/ điều mong đợi', '旅行が楽しみです。', 'minano-nihongo-35'],
    ['遊びます', 'あそびます', 'DU', 'chơi', '', 'minano-nihongo-13'],
    ['泳ぎます', 'およぎます', 'VĨNH', 'bơi', '', 'minano-nihongo-13'],
    ['水泳', 'すいえい', 'THỦY VỊNH', 'bơi/ môn bơi', '水泳を習っています。', 'minano-nihongo-36'],
    ['釣り', 'つり', 'ĐIẾU', 'việc câu cá', '', 'minano-nihongo-13'],
    ['野球', 'やきゅう', 'DÃ CẦU', 'bóng chày', '', 'minano-nihongo-9'],
    ['相撲', 'すもう', 'TƯƠNG PHÁC', 'Vật Sumo', '', 'minano-nihongo-19'],
    ['柔道', 'じゅうどう', 'NHU ĐẠO', 'judo/ nhu đạo', '柔道を習います。', 'minano-nihongo-26'],
    ['剣道', 'けんどう', 'KIẾM ĐẠO', 'kiếm đạo', '大学で剣道を始めました。', 'minano-nihongo-36'],
    ['運動します', 'うんどうします', 'VẬN ĐỘNG', 'vận động/ tập thể thao', '毎朝公園で運動しています。', 'minano-nihongo-32'],
    ['運動会', 'うんどうかい', 'VẬN ĐỘNG HỘI', 'hội thao/ đại hội thể thao', '学校で運動会があります。', 'minano-nihongo-26'],
    ['音楽', 'おんがく', 'ÂM NHẠC/LẠC', 'âm nhạc', '', 'minano-nihongo-9'],
    ['歌', 'うた', 'CA', 'bài hát', '', 'minano-nihongo-9'],
    ['歌います', 'うたいます', 'CA', 'Hát', '', 'minano-nihongo-18'],
    ['歌手', 'かしゅ', 'CA THỦ', 'ca sĩ', 'あの歌手は歌が上手です。', 'minano-nihongo-28'],
    ['踊ります', 'おどります', 'DŨNG', 'nhảy/ khiêu vũ', 'みんなで踊ります。', 'minano-nihongo-28'],
    ['曲', 'きょく', 'KHÚC', 'bài hát/ bản nhạc', '好きな曲を聞きます。', 'minano-nihongo-35'],
    ['映画', 'えいが', 'ẢNH HỌA', 'phim, điện ảnh', '', 'minano-nihongo-6'],
    ['漫画', 'まんが', 'MẠN HỌA', 'truyện tranh/ manga', '休みの日に漫画を読みます。', 'minano-nihongo-27'],
    ['小説', 'しょうせつ', 'TIỂU THUYẾT', 'tiểu thuyết', '面白い小説を読みます。', 'minano-nihongo-28'],
    ['小説家', 'しょうせつか', 'TIỂU THUYẾT GIA', 'tiểu thuyết gia/ nhà văn', '彼は有名な小説家です。', 'minano-nihongo-28'],
    ['作品', 'さくひん', 'TÁC PHẨM', 'tác phẩm', 'この作品はすばらしいです。', 'minano-nihongo-49'],
    ['番組', 'ばんぐみ', 'PHIÊN TỔ', 'chương trình phát thanh/ chương trình truyền hình', '面白い番組を見ます。', 'minano-nihongo-28'],
    ['絵', 'え', 'HỘI', 'Tranh, hội họa', '', 'minano-nihongo-9'],
    ['美術', 'びじゅつ', 'MỸ THUẬT', 'mỹ thuật', '', 'minano-nihongo-13'],
    ['美術館', 'びじゅつかん', 'MỸ THUẬT QUÁN', 'Bảo tàng mỹ thuật', '', 'minano-nihongo-4'],
    ['公園', 'こうえん', 'CÔNG VIÊN', 'công viên', '', 'minano-nihongo-10'],
  ]],
  ['cong-viec-cong-ty', [
    ['会社', 'かいしゃ', 'HỘI XÃ', 'công ty', '', 'minano-nihongo-3'],
    ['会社員', 'かいしゃいん', 'HỘI XÃ VIÊN', 'Nhân viên công ty', '', 'minano-nihongo-1'],
    ['社員', 'しゃいん', 'XÃ VIÊN', 'Nhân viên công ty ~', '', 'minano-nihongo-1'],
    ['本社', 'ほんしゃ', 'BẢN XÃ', 'trụ sở chính', '本社は大阪にあります。', 'minano-nihongo-31'],
    ['支店', 'してん', 'CHI ĐIẾM', 'chi nhánh', '東京に新しい支店ができました。', 'minano-nihongo-31'],
    ['事務所', 'じむしょ', 'SỰ VỤ SỞ', 'văn phòng', '', 'minano-nihongo-3'],
    ['工場', 'こうじょう', 'CÔNG TRƯỜNG', 'nhà máy/ phân xưởng', '父は自動車の工場で働いています。', 'minano-nihongo-36'],
    ['社長', 'しゃちょう', 'XÃ TRƯỞNG', 'Giám đốc', '', 'minano-nihongo-18'],
    ['部長', 'ぶちょう', 'BỘ TRƯỞNG', 'Trưởng phòng', '', 'minano-nihongo-18'],
    ['課長', 'かちょう', 'KHOA TRƯỜNG', 'Tổ trưởng', '', 'minano-nihongo-18'],
    ['管理人', 'かんりにん', 'QUẢN LÝ NHÂN', 'người quản lý', '寮の管理人と話します。', 'minano-nihongo-28'],
    ['係員', 'かかりいん', 'HỆ VIÊN', 'nhân viên phụ trách', '係員に聞いてください。', 'minano-nihongo-45'],
    ['会員', 'かいいん', 'HỘI VIÊN', 'hội viên/ thành viên', '会員になるために申し込みます。', 'minano-nihongo-42'],
    ['営業', 'えいぎょう', 'DOANH NGHIỆP', 'kinh doanh/ bán hàng', '営業の仕事をしています。', 'minano-nihongo-48'],
    ['会議', 'かいぎ', 'HỘI NGHỊ', 'họp, cuộc họp', '', 'minano-nihongo-13'],
    ['会議室', 'かいぎしつ', 'HỘI NGHỊ THẤT', 'phòng họp', '', 'minano-nihongo-3'],
    ['会議に出席します', 'かいぎにしゅっせきします', 'HỘI NGHỊ XUẤT TỊCH', 'tham dự cuộc họp/ tham gia cuộc họp', '部長の代わりに会議に出席します。', 'minano-nihongo-31'],
    ['席', 'せき', 'TỊCH', 'chỗ ngồi/ ghế', '窓側の席に座りたいです。', 'minano-nihongo-33'],
    ['席を外します', 'せきをはずします', 'TỊCH NGOẠI', 'rời khỏi chỗ ngồi/ đi vắng/ không có ở chỗ', '田中はただいま席を外しております。', 'minano-nihongo-33'],
    ['働きます', 'はたらきます', 'ĐỘNG', 'Làm việc', '', 'minano-nihongo-4'],
    ['会社に勤めます', 'かいしゃにつとめます', 'HỘI XÃ CẦN', 'làm việc ở công ty', '兄は自動車の会社に勤めています。', 'minano-nihongo-49'],
    ['会社をやめます', 'かいしゃをやめます', 'HỘI XÃ', 'Bỏ, thôi việc công ty', '', 'minano-nihongo-16'],
    ['残業します', 'ざんぎょうします', 'TÀN NGHIỆP', 'Làm thêm, làm quá giờ', '', 'minano-nihongo-17'],
    ['出張します', 'しゅっちょうします', 'XUẤT TRƯƠNG', 'Đi công tác', '', 'minano-nihongo-17'],
    ['転勤', 'てんきん', 'CHUYỂN CẦN', 'việc chuyển địa điểm làm việc', '', 'minano-nihongo-25'],
    ['給料', 'きゅうりょう', 'CẤP LIỆU', 'lương', '毎月給料をもらいます。', 'minano-nihongo-28'],
    ['収入', 'しゅうにゅう', 'THÂU NHẬP', 'thu nhập', '生活のために収入が必要です。', 'minano-nihongo-42'],
    ['名刺', 'めいし', 'DANH THÍCH', 'Danh thiếp', '', 'minano-nihongo-2'],
    ['資料', 'しりょう', 'TƯ LIỆU', 'Tài liệu, tư liệu', '', 'minano-nihongo-15'],
    ['書類', 'しょるい', 'THƯ LOẠI', 'giấy tờ/ tài liệu', '書類を整理するのは大変です。', 'minano-nihongo-38'],
    ['電子メール', 'でんしメール', 'ĐIỆN TỬ', 'thư điện tử/ email', '電子メールを送ります。', 'minano-nihongo-26'],
    ['はんこを押します', 'はんこをおします', 'ÁP', 'đóng dấu', 'ここにはんこを押してください。', 'minano-nihongo-38'],
    ['説明します', 'せつめいします', 'THUYẾT MINH', 'Giải thích, trình bày', '', 'minano-nihongo-24'],
    ['紹介します', 'しょうかいします', 'THIỆU GIỚI', 'Giới thiệu', '', 'minano-nihongo-24'],
    ['相談します', 'そうだんします', 'TƯƠNG ĐÀM', 'trao đổi/ bàn bạc/ tư vấn', '先生に相談します。', 'minano-nihongo-30'],
    ['連絡します', 'れんらくします', 'LIÊN LẠC', 'liên lạc/ liên hệ', 'すぐに連絡します。', 'minano-nihongo-26'],
    ['発表', 'はっぴょう', 'PHÁT BIỂU', 'phát biểu/ báo cáo', '研究の発表があります。', 'minano-nihongo-47'],
    ['返事', 'へんじ', 'PHẢN SỰ', 'hồi âm/ trả lời', 'まだ返事が来ません。', 'minano-nihongo-40'],
    ['申し込みます', 'もうしこみます', 'THÂN VÀO', 'đăng ký/ nộp đơn', '大会に申し込みます。', 'minano-nihongo-26'],
    ['申し込み', 'もうしこみ', 'THÂN VÀO', 'đăng ký', '申し込みは今日までです。', 'minano-nihongo-40'],
    ['成功します', 'せいこうします', 'THÀNH CÔNG', 'thành công', '実験は成功しました。', 'minano-nihongo-32'],
    ['予定', 'よてい', 'DỰ ĐỊNH', 'kế hoạch/ dự định', '明日の予定を話します。', 'minano-nihongo-30'],
    ['予定表', 'よていひょう', 'DỰ ĐỊNH BIỂU', 'lịch/ thời khóa biểu', '予定表を確認します。', 'minano-nihongo-30'],
    ['約束', 'やくそく', 'ƯỚC THÚC', 'cuộc hẹn, lời hứa', '', 'minano-nihongo-9'],
    ['用事', 'ようじ', 'DỤNG SỰ', 'việc bận, công chuyện', '', 'minano-nihongo-9'],
    ['急用', 'きゅうよう', 'CẤP DỤNG', 'việc gấp/ việc khẩn', '急用ができて、行けなくなりました。', 'minano-nihongo-33'],
    ['都合がいい', 'つごうがいい', 'ĐÔ HỢP', 'tiện/ thuận tiện/ có thời gian', '明日、都合がいいですか。', 'minano-nihongo-26'],
    ['都合が悪い', 'つごうがわるい', 'ĐÔ HỢP ÁC', 'không tiện/ bận/ vướng việc', 'その日は都合が悪いです。', 'minano-nihongo-26'],
    ['貿易', 'ぼうえき', 'MẬU DỊCH', 'mậu dịch/ thương mại quốc tế', '貿易の会社で働いています。', 'minano-nihongo-49'],
    ['輸出します', 'ゆしゅつします', 'THÂU XUẤT', 'xuất khẩu', '日本は車を輸出しています。', 'minano-nihongo-37'],
    ['輸入します', 'ゆにゅうします', 'THÂU NHẬP', 'nhập khẩu', '石油を輸入しています。', 'minano-nihongo-37'],
    ['製品', 'せいひん', 'CHẾ PHẨM', 'Sản phẩm', '', 'minano-nihongo-15'],
    ['品物', 'しなもの', 'PHẨM VẬT', 'hàng hóa/ mặt hàng', '品物を見ます。', 'minano-nihongo-28'],
    ['技術', 'ぎじゅつ', 'KỸ THUẬT', 'kỹ thuật', '日本の技術は進んでいます。', 'minano-nihongo-37'],
    ['機械', 'きかい', 'CƠ GIỚI', 'Máy, máy móc', '', 'minano-nihongo-23'],
    ['故障', 'こしょう', 'CỐ CHƯỚNG', 'Hỏng', '', 'minano-nihongo-23'],
    ['修理します', 'しゅうりします', 'TU LÝ', 'Sửa chữa, tu sửa', '', 'minano-nihongo-20'],
    ['直します', 'なおします', 'TRỰC', 'Sửa, chữa', '', 'minano-nihongo-20'],
  ]],
  ['truong-hoc-hoc-tap', [
    ['学校', 'がっこう', 'HỌC HIỆU', 'trường học', '', 'minano-nihongo-5'],
    ['小学校', 'しょうがっこう', 'TIỂU HỌC HIỆU', 'trường tiểu học', '娘は小学校に通っています。', 'minano-nihongo-38'],
    ['中学校', 'ちゅうがっこう', 'TRUNG HỌC HIỆU', 'trường trung học cơ sở', '息子は中学校の先生です。', 'minano-nihongo-38'],
    ['高校', 'こうこう', 'CAO HIỆU', 'Trường trung học phổ thông', '', 'minano-nihongo-15'],
    ['大学', 'だいがく', 'ĐẠI HỌC', 'Đại học, Trường đại học', '', 'minano-nihongo-1'],
    ['大学院', 'だいがくいん', 'ĐẠI HỌC VIỆN', 'cao học/ sau đại học', '大学院で経済を研究するつもりです。', 'minano-nihongo-31'],
    ['塾', 'じゅく', 'THỤC', 'cơ sở học thêm', '息子を塾に通わせています。', 'minano-nihongo-48'],
    ['学生', 'がくせい', 'HỌC SINH', 'Học sinh, sinh viên', '', 'minano-nihongo-1'],
    ['大学生', 'だいがくせい', 'ĐẠI HỌC SINH', 'sinh viên đại học', '息子は大学生です。', 'minano-nihongo-45'],
    ['留学生', 'りゅうがくせい', 'LƯU HỌC SINH', 'du học sinh', '', 'minano-nihongo-16'],
    ['生徒', 'せいと', 'SINH ĐỒ', 'học sinh/ học trò', '先生は生徒に本を読ませました。', 'minano-nihongo-48'],
    ['教師', 'きょうし', 'GIÁO SƯ', 'Giáo viên', '', 'minano-nihongo-1'],
    ['先生', 'せんせい', 'TIÊN SINH', 'Thầy/ cô', '', 'minano-nihongo-1'],
    ['講師', 'こうし', 'GIẢNG SƯ', 'giảng viên/ giáo viên', '大学の講師をしていらっしゃいます。', 'minano-nihongo-49'],
    ['研究者', 'けんきゅうしゃ', 'NGHIÊN CỨU GIẢ', 'Nhà nghiên cứu', '', 'minano-nihongo-1'],
    ['博士', 'はかせ', 'BÁC SĨ', 'tiến sĩ', '博士の研究が発表されました。', 'minano-nihongo-47'],
    ['教室', 'きょうしつ', 'GIÁO THẤT', 'lớp học, phòng học', '', 'minano-nihongo-3'],
    ['授業', 'じゅぎょう', 'THỤ NGHIỆP', 'giờ học', 'もうすぐ授業が始まります。', 'minano-nihongo-30'],
    ['講義', 'こうぎ', 'GIẢNG NGHĨA', 'bài giảng', '大学で講義を聞きます。', 'minano-nihongo-30'],
    ['宿題', 'しゅくだい', 'TÚC ĐỀ', 'bài tập về nhà', '', 'minano-nihongo-6'],
    ['作文', 'さくぶん', 'TÁC VĂN', 'bài văn/ bài tập làm văn', '作文を書く宿題があります。', 'minano-nihongo-31'],
    ['専門', 'せんもん', 'CHUYÊN MÔN', 'Chuyên môn', '', 'minano-nihongo-15'],
    ['試験', 'しけん', 'THÍ NGHIỆM', 'Kỳ thi, bài thi', '', 'minano-nihongo-12'],
    ['試験を受けます', 'しけんをうけます', 'THỨC NGHIỆM THỤ', 'thi/ dự kỳ thi', '来月、日本語の試験を受けます。', 'minano-nihongo-31'],
    ['試験に合格します', 'しけんにごうかくします', 'THỨC NGHIỆM HỢP CÁCH', 'đỗ thi/ đậu kỳ thi', '息子が試験に合格しました。', 'minano-nihongo-32'],
    ['試験に失敗します', 'しけんにしっぱいします', 'THỨC NGHIỆM THẤT BẠI', 'thất bại/ trượt thi', '試験に失敗してしまいました。', 'minano-nihongo-32'],
    ['成績', 'せいせき', 'THÀNH TÍCH', 'kết quả/ thành tích', '試験の成績がよかったです。', 'minano-nihongo-40'],
    ['勉強', 'べんきょう', 'MIỄN CƯỜNG', 'học', '', 'minano-nihongo-8'],
    ['勉強します', 'べんきょうします', 'MIỄN CƯỜNG', 'Học', '', 'minano-nihongo-4'],
    ['予習します', 'よしゅうします', 'DỰ TẬP', 'chuẩn bị bài mới', '明日勉強するところを予習します。', 'minano-nihongo-30'],
    ['復習します', 'ふくしゅうします', 'PHỤC TẬP', 'ôn bài cũ', '今日習ったことを復習します。', 'minano-nihongo-30'],
    ['練習します', 'れんしゅうします', 'LUYỆN TẬP', 'Luyện tập, thực hành', '', 'minano-nihongo-19'],
    ['習う', 'ならう', 'TẬP', 'học, tập', '', 'minano-nihongo-7'],
    ['教える', 'おしえる', 'GIÁO', 'dạy', '', 'minano-nihongo-7'],
    ['覚えます', 'おぼえます', 'GIÁC', 'Nhớ', '', 'minano-nihongo-17'],
    ['忘れます', 'わすれます', 'VONG', 'Quên', '', 'minano-nihongo-17'],
    ['質問します', 'しつもんします', 'CHẤT VẤN', 'hỏi/ đặt câu hỏi', '分からないことは先生に質問します。', 'minano-nihongo-34'],
    ['質問に答えます', 'しつもんにこたえます', 'CHẤT VẤN ĐÁP', 'trả lời câu hỏi', '学生の質問に答えました。', 'minano-nihongo-39'],
    ['答え', 'こたえ', 'ĐÁP', 'Câu trả lời', '', 'minano-nihongo-17'],
    ['回答', 'かいとう', 'HỒI ĐÁP', 'câu trả lời/ lời giải', '回答を紙に書いてください。', 'minano-nihongo-45'],
    ['大学に入学します', 'だいがくににゅうがくします', 'ĐẠI HỌC NHẬP HỌC', 'nhập học/ vào đại học', '来年、大学に入学するつもりです。', 'minano-nihongo-31'],
    ['大学を卒業します', 'だいがくをそつぎょうします', 'ĐẠI HỌC TỐT NGHIỆP', 'tốt nghiệp đại học', '去年、大学を卒業しました。', 'minano-nihongo-31'],
    ['大学に通います', 'だいがくにかよいます', 'ĐẠI HỌC THÔNG', 'đi đi về về trường đại học', '毎日大学に通います。', 'minano-nihongo-28'],
    ['留学します', 'りゅうがくします', 'LƯU HỌC', 'du học', '', 'minano-nihongo-25'],
    ['文法', 'ぶんぽう', 'VĂN PHÁP', 'ngữ pháp', '文法が難しいです。', 'minano-nihongo-41'],
    ['発音', 'はつおん', 'PHÁT ÂM', 'phát âm', '発音を直していただきました。', 'minano-nihongo-41'],
    ['漢字', 'かんじ', 'HÁN TỰ', 'chữ hán', '', 'minano-nihongo-9'],
    ['字', 'じ', 'TỰ', 'chữ', '', 'minano-nihongo-9'],
    ['読み方', 'よみかた', 'ĐỘC PHƯƠNG', 'Cách đọc', '', 'minano-nihongo-14'],
    ['意味', 'いみ', 'Ý VỊ', 'Ý nghĩa', '', 'minano-nihongo-24'],
    ['辞書', 'じしょ', 'TỪ THƯ', 'Từ điển', '', 'minano-nihongo-2'],
    ['本', 'ほん', 'BẢN/BỔN', 'Sách', '', 'minano-nihongo-2'],
    ['図書館', 'としょかん', 'ĐỒ THƯ QUÁN', 'Thư viện', '', 'minano-nihongo-4'],
    ['研究します', 'けんきゅうします', 'NGHIÊN CỨU', 'Nghiên cứu', '', 'minano-nihongo-15'],
    ['研究室', 'けんきゅうしつ', 'NGHIÊN CỨU THẤT', 'phòng nghiên cứu', '先生は研究室にいらっしゃいます。', 'minano-nihongo-38'],
    ['知識', 'ちしき', 'TRI THỨC', 'tri thức/ kiến thức', '知識が豊富な人です。', 'minano-nihongo-46'],
    ['経験', 'けいけん', 'KINH NGHIỆM', 'kinh nghiệm', '仕事の経験があります。', 'minano-nihongo-28'],
    ['科学', 'かがく', 'KHOA HỌC', 'khoa học', '科学の本を読みます。', 'minano-nihongo-47'],
    ['医学', 'いがく', 'Y HỌC', 'y học', '医学を勉強しています。', 'minano-nihongo-47'],
    ['文学', 'ぶんがく', 'VĂN HỌC', 'văn học', '大学で文学を専門にしました。', 'minano-nihongo-47'],
    ['歴史', 'れきし', 'LỊCH SỬ', 'lịch sử', '日本の歴史を勉強しています。', 'minano-nihongo-36'],
  ]],
  ['mua-sam-tien-bac', [
    ['買い物します', 'かいものします', 'MÃI VẬT', 'mua hàng', '', 'minano-nihongo-13'],
    ['買う', 'かう', 'MÃI', 'mua', '', 'minano-nihongo-6'],
    ['売ります', 'うります', 'MẠI', 'Bán', '', 'minano-nihongo-15'],
    ['売れます', 'うれます', 'MẠI', 'bán chạy/ được bán', 'このパンはよく売れます。', 'minano-nihongo-28'],
    ['店', 'みせ', 'ĐIẾM', 'cửa hàng, tiệm', '', 'minano-nihongo-6'],
    ['売り場', 'うりば', 'MẠI TRƯỜNG', 'quầy bán (trong một cửa hàng bách hóa)', '', 'minano-nihongo-3'],
    ['本屋', 'ほんや', 'BỔN ỐC', 'hiệu sách', '', 'minano-nihongo-10'],
    ['電気屋', 'でんきや', 'ĐIỆN KHÍ ỐC', 'Cửa hàng đồ điện', '', 'minano-nihongo-23'],
    ['喫茶店', 'きっさてん', 'KHIẾT TRÀ ĐIẾM', 'quán giải khát, quán cà phê', '', 'minano-nihongo-10'],
    ['自動販売機', 'じどうはんばいき', 'TỰ ĐỘNG PHIÊN MẠI CƠ', 'máy bán hàng tự động', '駅で自動販売機を使います。', 'minano-nihongo-27'],
    ['通信販売', 'つうしんはんばい', 'THÔNG TÍN PHIÊN MẠI', 'bán hàng qua bưu điện/ thương mại viễn thông', '最近、通信販売をよく利用します。', 'minano-nihongo-27'],
    ['お客様', 'おきゃくさま', 'KHÁCH DẠNG', 'quý khách/ khách hàng', 'お客様がいらっしゃいました。', 'minano-nihongo-36'],
    ['品物', 'しなもの', 'PHẨM VẬT', 'hàng hóa/ mặt hàng', '品物を見ます。', 'minano-nihongo-28'],
    ['製品', 'せいひん', 'CHẾ PHẨM', 'Sản phẩm', '', 'minano-nihongo-15'],
    ['値段', 'ねだん', 'TRỊ ĐOẠN', 'giá/ giá cả', 'この服は値段が高いです。', 'minano-nihongo-28'],
    ['値段が上がります', 'ねだんがあがります', 'TRỊ ĐOẠN THƯỢNG', 'giá tăng lên', '野菜の値段が上がりました。', 'minano-nihongo-42'],
    ['値段が下がります', 'ねだんがさがります', 'TRỊ ĐOẠN HẠ', 'giá giảm xuống', 'パソコンの値段が下がりました。', 'minano-nihongo-42'],
    ['高い', 'たかい', 'CAO', 'đắt, cao', '', 'minano-nihongo-8'],
    ['安い', 'やすい', 'AN', 'rẻ', '', 'minano-nihongo-8'],
    ['お金', 'おかね', 'KIM', 'tiền', '', 'minano-nihongo-7'],
    ['現金', 'げんきん', 'HIỆN KIM', 'Tiền mặt', '', 'minano-nihongo-18'],
    ['お釣り', 'おつり', 'ĐIẾU', 'Tiền lẻ', '', 'minano-nihongo-14'],
    ['細かいお金', 'こまかいおかね', 'TẾ KIM', 'tiền lẻ', '', 'minano-nihongo-9'],
    ['金額', 'きんがく', 'KIM NGẠCH', 'Số tiền, khoản tiền', '', 'minano-nihongo-16'],
    ['暗証番号', 'あんしょうばんごう', 'ÁM CHỨNG PHIÊN HIỆU', 'Mật khẩu', '', 'minano-nihongo-16'],
    ['払います', 'はらいます', 'PHẤT', 'Trả tiền', '', 'minano-nihongo-17'],
    ['返します', 'かえします', 'PHẢN', 'Trả lại', '', 'minano-nihongo-17'],
    ['貸す', 'かす', 'THẢI', 'cho mượn, cho vay', '', 'minano-nihongo-7'],
    ['借りる', 'かりる', 'TÁ', 'mượn, vay', '', 'minano-nihongo-7'],
    ['貯金します', 'ちょきんします', 'TRỮ KIM', 'tiết kiệm tiền/ để dành tiền', '車を買うために貯金しています。', 'minano-nihongo-36'],
    ['物価', 'ぶっか', 'VẬT GIÁ', 'Giá cả, mức giá, vật giá', '', 'minano-nihongo-20'],
    ['家賃', 'やちん', 'GIA NHẦM', 'Tiền thuê nhà', '', 'minano-nihongo-22'],
    ['電話代', 'でんわだい', 'ĐIỆN THOẠI ĐẠI', 'tiền điện thoại', '今月は電話代が高かったです。', 'minano-nihongo-39'],
    ['給料', 'きゅうりょう', 'CẤP LIỆU', 'lương', '毎月給料をもらいます。', 'minano-nihongo-28'],
    ['収入', 'しゅうにゅう', 'THÂU NHẬP', 'thu nhập', '生活のために収入が必要です。', 'minano-nihongo-42'],
    ['無料', 'むりょう', 'VÔ LIỆU', 'miễn phí', 'このサービスは無料です。', 'minano-nihongo-28'],
    ['半分', 'はんぶん', 'BÁN PHÂN', 'một nửa', 'ケーキを半分に切ります。', 'minano-nihongo-44'],
    ['全部で', 'ぜんぶで', 'TOÀN BỘ', 'tổng cộng', '', 'minano-nihongo-11'],
    ['領収書', 'りょうしゅうしょ', 'LÃNH THÂU THƯ', 'hóa đơn/ biên lai', '領収書をお願いします。', 'minano-nihongo-45'],
    ['保証書', 'ほしょうしょ', 'BẢO CHỨNG THƯ', 'giấy bảo hành', '保証書を持って来てください。', 'minano-nihongo-45'],
    ['贈り物', 'おくりもの', 'TẶNG VẬT', 'quà tặng', '贈り物を送りました。', 'minano-nihongo-45'],
    ['お祝い', 'おいわい', 'CHÚC', 'quà mừng/ lời chúc mừng/ lễ mừng', '結婚のお祝いを送りました。', 'minano-nihongo-33'],
    ['お年玉', 'おとしだま', 'NIÊN NGỌC', 'tiền mừng tuổi', '子どもにお年玉をあげます。', 'minano-nihongo-41'],
    ['宝くじ', 'たからくじ', 'BẢO', 'xổ số', '宝くじが当たったら、家を買います。', 'minano-nihongo-32'],
    ['お金持ち', 'おかねもち', 'KIM TRÌ', 'người giàu có', 'お金持ちになりたいです。', 'minano-nihongo-32'],
    ['銀行', 'ぎんこう', 'NGÂN HÀNH', 'Ngân hàng', '', 'minano-nihongo-4'],
    ['銀行員', 'ぎんこういん', 'NGÂN HÀNH VIÊN', 'Nhân viên ngân hàng', '', 'minano-nihongo-1'],
    ['郵便局', 'ゆうびんきょく', 'BƯU TIỆN CỤC', 'Bưu điện', '', 'minano-nihongo-4'],
    ['切手', 'きって', 'THIẾT THỦ', 'tem', '', 'minano-nihongo-11'],
    ['封筒', 'ふうとう', 'PHONG ĐỒNG', 'phong bì', '', 'minano-nihongo-11'],
    ['速達', 'そくたつ', 'TỐC ĐẠT', 'gửi nhanh', '', 'minano-nihongo-11'],
    ['書留', 'かきとめ', 'THƯ LƯU', 'gửi bảo đảm', '', 'minano-nihongo-11'],
    ['宅配便', 'たくはいびん', 'TRẠCH PHỐI TIỆN', 'dịch vụ chuyển đồ đến nhà', '宅配便で荷物を送ります。', 'minano-nihongo-46'],
  ]],
  ['thanh-pho-cong-cong', [
    ['町', 'まち', 'ĐINH', 'thị trấn, thị xã, thành phố', '', 'minano-nihongo-8'],
    ['村', 'むら', 'THÔN', 'làng', '祖父は小さい村に住んでいます。', 'minano-nihongo-35'],
    ['島', 'しま', 'ĐẢO', 'đảo/ hòn đảo', '船で島へ行きます。', 'minano-nihongo-35'],
    ['県', 'けん', 'HUYỆN', 'tỉnh', '', 'minano-nihongo-10'],
    ['田舎', 'いなか', 'ĐIỀN XÁ', 'quê, nông thôn', '', 'minano-nihongo-25'],
    ['郊外', 'こうがい', 'GIAO NGOẠI', 'ngoại ô', '郊外に住んでいます。', 'minano-nihongo-50'],
    ['近所', 'きんじょ', 'CẬN SỞ', 'khu lân cận/ gần nhà', '近所に新しい店ができました。', 'minano-nihongo-35'],
    ['建物', 'たてもの', 'KIẾN VẬT', 'Tòa nhà', '', 'minano-nihongo-23'],
    ['人口', 'じんこう', 'NHÂN KHẨU', 'dân số', 'この町の人口は増えているようです。', 'minano-nihongo-47'],
    ['大勢', 'おおぜい', 'ĐẠI THẾ', 'nhiều người', '会場に大勢の人が集まりました。', 'minano-nihongo-39'],
    ['交番', 'こうばん', 'GIAO PHIÊN', 'đồn cảnh sát', '交番で道を尋ねます。', 'minano-nihongo-30'],
    ['警察', 'けいさつ', 'CẢNH SÁT', 'cảnh sát', 'すぐに警察に電話してください。', 'minano-nihongo-33'],
    ['警官', 'けいかん', 'CẢNH QUAN', 'cảnh sát', '警官に道を聞かれました。', 'minano-nihongo-37'],
    ['市役所', 'しやくしょ', 'THỊ DỊCH SỞ', 'văn phòng hành chính quận, thành phố', '', 'minano-nihongo-13'],
    ['大使館', 'たいしかん', 'ĐẠI SỨ QUÁN', 'đại sứ quán', '', 'minano-nihongo-25'],
    ['入管', 'にゅうかん', 'NHẬP QUẢN', 'Cục quản lý nhập cảnh', '入管でビザの手続きをします。', 'minano-nihongo-48'],
    ['病院', 'びょういん', 'BỆNH VIỆN', 'Bệnh viện', '', 'minano-nihongo-1'],
    ['銀行', 'ぎんこう', 'NGÂN HÀNH', 'Ngân hàng', '', 'minano-nihongo-4'],
    ['郵便局', 'ゆうびんきょく', 'BƯU TIỆN CỤC', 'Bưu điện', '', 'minano-nihongo-4'],
    ['図書館', 'としょかん', 'ĐỒ THƯ QUÁN', 'Thư viện', '', 'minano-nihongo-4'],
    ['美術館', 'びじゅつかん', 'MỸ THUẬT QUÁN', 'Bảo tàng mỹ thuật', '', 'minano-nihongo-4'],
    ['体育館', 'たいいくかん', 'THỂ DỤC QUÁN', 'nhà tập/ nhà thi đấu thể thao', '体育館で運動をします。', 'minano-nihongo-28'],
    ['会場', 'かいじょう', 'HỘI TRƯỜNG', 'hội trường', '会場はあちらです。', 'minano-nihongo-49'],
    ['公園', 'こうえん', 'CÔNG VIÊN', 'công viên', '', 'minano-nihongo-10'],
    ['動物園', 'どうぶつえん', 'ĐỘNG VẬT VIÊN', 'vườn thú/ vườn bách thú', '子どもと動物園へ行きました。', 'minano-nihongo-31'],
    ['教会', 'きょうかい', 'GIÁO HỘI', 'nhà thờ', '日曜日に教会へ行きます。', 'minano-nihongo-31'],
    ['お寺', 'おてら', 'TỰ', 'Chùa', '', 'minano-nihongo-16'],
    ['神社', 'じんじゃ', 'THẦN XÃ', 'Đền thờ đạo thần', '', 'minano-nihongo-16'],
    ['お城', 'おしろ', 'THÀNH', 'lâu đài/ thành', '日曜日にお城を見に行きました。', 'minano-nihongo-41'],
    ['駐車場', 'ちゅうしゃじょう', 'TRÚ XA TRƯỜNG', 'Bãi đỗ xe', '', 'minano-nihongo-23'],
    ['入口', 'いりぐち', 'NHẬP KHẨU', 'lối vào/ cửa vào', '入口はあちらです。', 'minano-nihongo-33'],
    ['出口', 'でぐち', 'XUẤT KHẨU', 'lối ra/ cửa ra', '出口はどこですか。', 'minano-nihongo-33'],
    ['非常口', 'ひじょうぐち', 'PHI THƯỜNG KHẨU', 'lối thoát hiểm/ cửa thoát hiểm', '地震のときは非常口から出てください。', 'minano-nihongo-33'],
    ['階段', 'かいだん', 'GIAI ĐOẠN', 'Cầu thang', '', 'minano-nihongo-3'],
    ['お手洗い', 'おてあらい', 'THỦ TẢY', 'nhà vệ sinh, phòng vệ sinh, toa-lét', '', 'minano-nihongo-3'],
    ['受付', 'うけつけ', 'THỤ PHÓ', 'bộ phận tiếp tân, phòng thường trực', '', 'minano-nihongo-3'],
    ['食堂', 'しょくどう', 'THỰC ĐƯỜNG', 'nhà ăn', '', 'minano-nihongo-3'],
    ['寮', 'りょう', 'LIÊU', 'kí túc xá', '', 'minano-nihongo-8'],
    ['交差点', 'こうさてん', 'GIAO SAI ĐIỂM', 'Ngã tư', '', 'minano-nihongo-23'],
    ['信号', 'しんごう', 'TÍN HIỆU', 'Đèn tín hiệu', '', 'minano-nihongo-23'],
    ['橋', 'はし', 'KIỀU', 'Cầu', '', 'minano-nihongo-23'],
    ['道', 'みち', 'ĐẠO', 'Đường', '', 'minano-nihongo-23'],
    ['地図', 'ちず', 'ĐỊA ĐỒ', 'Bản đồ', '', 'minano-nihongo-14'],
    ['住所', 'じゅうしょ', 'TRÚ SỞ', 'Địa chỉ', '', 'minano-nihongo-14'],
    ['立入禁止', 'たちいりきんし', 'LẬP NHẬP CẤM CHỈ', 'cấm vào/ cấm vào khu vực này', '工事中ですから、立入禁止です。', 'minano-nihongo-33'],
    ['使用禁止', 'しようきんし', 'SỬ DỤNG CẤM CHỈ', 'cấm sử dụng', 'このトイレは使用禁止です。', 'minano-nihongo-33'],
    ['禁煙', 'きんえん', 'CẤM YÊN', 'Cấm hút thuốc', '', 'minano-nihongo-17'],
    ['営業中', 'えいぎょうちゅう', 'DOANH NGHIỆP TRUNG', 'đang mở cửa/ đang kinh doanh', 'あの店はまだ営業中です。', 'minano-nihongo-33'],
    ['本日休業', 'ほんじつきゅうぎょう', 'BẢN NHẬT HƯU NGHIỆP', 'hôm nay nghỉ/ hôm nay đóng cửa', '本日休業と書いてあります。', 'minano-nihongo-33'],
    ['使用中', 'しようちゅう', 'SỬ DỤNG TRUNG', 'đang sử dụng/ đang có người dùng', '会議室は使用中です。', 'minano-nihongo-33'],
    ['規則', 'きそく', 'QUY TẮC', 'quy định/ nội quy/ quy tắc', '会社の規則を守らなければなりません。', 'minano-nihongo-33'],
    ['泥棒', 'どろぼう', 'NÊ BỔNG', 'kẻ trộm', '泥棒に財布を取られました。', 'minano-nihongo-37'],
    ['犯人', 'はんにん', 'PHẠM NHÂN', 'thủ phạm', '犯人はまだ見つかりません。', 'minano-nihongo-40'],
    ['罰金', 'ばっきん', 'PHẠT KIM', 'tiền phạt', 'スピード違反で罰金を払いました。', 'minano-nihongo-33'],
    ['事件', 'じけん', 'SỰ KIỆN', 'vụ án/ vụ việc', '大きい事件が起きました。', 'minano-nihongo-40'],
    ['政治', 'せいじ', 'CHÍNH TRỊ', 'Chính trị', '', 'minano-nihongo-21'],
    ['首相', 'しゅしょう', 'THỦ TƯỚNG', 'Thủ tướng', '', 'minano-nihongo-21'],
    ['大統領', 'だいとうりょう', 'ĐẠI THỐNG LÃNH', 'Tổng thống', '', 'minano-nihongo-21'],
  ]],
  ['thoi-gian-ngay-thang', [
    ['時間', 'じかん', 'THÌ/THỜI GIAN', 'thời gian', '', 'minano-nihongo-9'],
    ['今', 'いま', 'KIM', 'Bây giờ', '', 'minano-nihongo-4'],
    ['明日', 'あした', 'MINH NHẬT', 'ngày mai', '明日は雨が降るそうです。', 'minano-nihongo-33'],
    ['日', 'ひ', 'NHẬT', 'Ngày', '', 'minano-nihongo-19'],
    ['日にち', 'ひにち', 'NHẬT', 'ngày', '会議の日にちを決めます。', 'minano-nihongo-28'],
    ['秒', 'びょう', 'MIỂU', 'giây', 'あと30秒で始まります。', 'minano-nihongo-46'],
    ['朝', 'あさ', 'TRIỀU', 'Buổi sáng, sáng', '', 'minano-nihongo-4'],
    ['昼', 'ひる', 'TRÚ', 'Buổi trưa, trưa', '', 'minano-nihongo-4'],
    ['晩', 'ばん', 'VÃN', 'Buổi tối, tối', '', 'minano-nihongo-4'],
    ['夜', 'よる', 'DẠ', 'Buổi tối, khuya', '', 'minano-nihongo-4'],
    ['今晩', 'こんばん', 'KIM VÃN', 'Tối nay', '', 'minano-nihongo-4'],
    ['今夜', 'こんや', 'KIM DẠ', 'tối nay/ đêm nay', '今夜はうちで食事します。', 'minano-nihongo-32'],
    ['夕方', 'ゆうがた', 'TỊCH PHƯƠNG', 'chiều tối', '夕方までに帰ります。', 'minano-nihongo-32'],
    ['昼間', 'ひるま', 'TRÚ GIAN', 'ban ngày/ thời gian ban ngày', '昼間は暑いです。', 'minano-nihongo-27'],
    ['午前', 'ごぜん', 'NGỌ TIỀN', 'Sáng, trước 12 giờ trưa', '', 'minano-nihongo-4'],
    ['午後', 'ごご', 'NGỌ HẬU', 'Chiều, sau 12 giờ trưa', '', 'minano-nihongo-4'],
    ['毎日', 'まいにち', 'MỖI NHẬT', 'Hàng ngày, mỗi ngày', '', 'minano-nihongo-4'],
    ['毎朝', 'まいあさ', 'MỖI TRIỀU', 'Hàng sáng, mỗi sáng', '', 'minano-nihongo-4'],
    ['毎晩', 'まいばん', 'MỖI VÃN', 'Hàng tối, mỗi tối', '', 'minano-nihongo-4'],
    ['毎週', 'まいしゅう', 'MỖI CHU', 'hàng tuần', '毎週日曜日にプールへ行きます。', 'minano-nihongo-36'],
    ['毎月', 'まいつき', 'MỖI NGUYỆT', 'hàng tháng', '毎月少しずつ貯金します。', 'minano-nihongo-36'],
    ['毎年', 'まいとし', 'MỖI NIÊN', 'hàng năm', '毎年国へ帰ります。', 'minano-nihongo-36'],
    ['先週', 'せんしゅう', 'TIÊN CHU', 'tuần trước', '', 'minano-nihongo-5'],
    ['今週', 'こんしゅう', 'KIM CHU', 'tuần này', '', 'minano-nihongo-5'],
    ['来週', 'らいしゅう', 'LAI CHU', 'tuần sau', '', 'minano-nihongo-5'],
    ['再来週', 'さらいしゅう', 'TÁI LAI CHU', 'tuần sau nữa', '再来週、国へ帰ります。', 'minano-nihongo-50'],
    ['先月', 'せんげつ', 'TIÊN NGUYỆT', 'tháng trước', '', 'minano-nihongo-5'],
    ['今月', 'こんげつ', 'KIM NGUYỆT', 'tháng này', '', 'minano-nihongo-5'],
    ['来月', 'らいげつ', 'LAI NGUYỆT', 'tháng sau', '', 'minano-nihongo-5'],
    ['再来月', 'さらいげつ', 'TÁI LAI NGUYỆT', 'tháng sau nữa', '再来月から新しい仕事を始めます。', 'minano-nihongo-50'],
    ['去年', 'きょねん', 'KHU NIÊN', 'năm ngoái', '', 'minano-nihongo-5'],
    ['来年', 'らいねん', 'LAI NIÊN', 'năm sau', '', 'minano-nihongo-5'],
    ['再来年', 'さらいねん', 'TÁI LAI NIÊN', 'năm sau nữa', '再来年、また日本へ参ります。', 'minano-nihongo-50'],
    ['半年', 'はんとし', 'BÁN NIÊN', 'nửa năm', '日本に来て半年になります。', 'minano-nihongo-50'],
    ['週末', 'しゅうまつ', 'CHU MẠT', 'cuối tuần', '', 'minano-nihongo-13'],
    ['月曜日', 'げつようび', 'NGUYỆT DIỆU NHẬT', 'Thứ hai', '', 'minano-nihongo-4'],
    ['火曜日', 'かようび', 'HỎA DIỆU NHẬT', 'Thứ ba', '', 'minano-nihongo-4'],
    ['水曜日', 'すいようび', 'THỦY DIỆU NHẬT', 'Thứ tư', '', 'minano-nihongo-4'],
    ['木曜日', 'もくようび', 'MỘC DIỆU NHẬT', 'Thứ năm', '', 'minano-nihongo-4'],
    ['金曜日', 'きんようび', 'KIM DIỆU NHẬT', 'Thứ sáu', '', 'minano-nihongo-4'],
    ['土曜日', 'どようび', 'THỔ DIỆU NHẬT', 'Thứ bảy', '', 'minano-nihongo-4'],
    ['日曜日', 'にちようび', 'NHẬT DIỆU NHẬT', 'Chủ Nhật', '', 'minano-nihongo-4'],
    ['何曜日', 'なんようび', 'HÀ DIỆU NHẬT', 'Thứ mấy', '', 'minano-nihongo-4'],
    ['誕生日', 'たんじょうび', 'ĐẢN SINH NHẬT', 'sinh nhật', '', 'minano-nihongo-5'],
    ['予定', 'よてい', 'DỰ ĐỊNH', 'kế hoạch/ dự định', '明日の予定を話します。', 'minano-nihongo-30'],
    ['最近', 'さいきん', 'TỐI CẬN', 'Gần đây', '', 'minano-nihongo-21'],
    ['昔', 'むかし', 'TÍCH', 'ngày xưa/ trước đây', '昔、ここに公園がありました。', 'minano-nihongo-27'],
    ['将来', 'しょうらい', 'TƯƠNG LAI', 'tương lai', '将来、医者になりたいです。', 'minano-nihongo-27'],
    ['先日', 'せんじつ', 'TIÊN NHẬT', 'hôm trước/ mấy hôm trước', '先日はごちそうさまでした。', 'minano-nihongo-41'],
    ['この間', 'このあいだ', 'GIAN', 'Vừa rồi, hôm nọ', '', 'minano-nihongo-20'],
    ['たった今', 'たったいま', 'KIM', 'vừa mới rồi', 'たった今着いたところです。', 'minano-nihongo-46'],
    ['ただ今', 'ただいま', 'KIM', 'bây giờ/ vừa mới', 'ただ今、社長は席を外しております。', 'minano-nihongo-50'],
    ['最初に', 'さいしょに', 'TỐI SƠ', 'đầu tiên/ trước hết', '最初に自己紹介をいたします。', 'minano-nihongo-50'],
    ['最後に', 'さいごに', 'TỐI HẬU', 'cuối cùng', '最後にお礼を申し上げます。', 'minano-nihongo-50'],
    ['初めに', 'はじめに', 'SƠ', 'đầu tiên/ trước hết', '初めに名前を書いてください。', 'minano-nihongo-35'],
    ['始め', 'はじめ', 'THỦY', 'Ban đầu, đầu tiên', '', 'minano-nihongo-20'],
    ['終わり', 'おわり', 'CHUNG', 'Kết thúc', '', 'minano-nihongo-20'],
    ['時間がたちます', 'じかんがたちます', 'THỜI GIAN', 'thời gian trôi đi', '時間がたつのは速いですね。', 'minano-nihongo-38'],
    ['遅く', 'おそく', 'TRÌ', 'muộn/ khuya', '昨夜は遅くまで働きました。', 'minano-nihongo-32'],
    ['早い', 'はやい', 'TẢO', 'sớm', '', 'minano-nihongo-12'],
    ['遅い', 'おそい', 'TRÌ', 'Chậm, muộn', '', 'minano-nihongo-12'],
    ['急に', 'きゅうに', 'CẤP', 'đột nhiên/ gấp', '急に雨が降ってきました。', 'minano-nihongo-40'],
    ['久しぶり', 'ひさしぶり', 'CỬU', 'lâu rồi (mới gặp lại)', '久しぶりに友達に会いました。', 'minano-nihongo-48'],
  ]],
  ['so-luong-don-vi', [
    ['百', 'ひゃく', 'BÁCH', 'Trăm', '', 'minano-nihongo-3'],
    ['千', 'せん', 'THIÊN', 'nghìn', '', 'minano-nihongo-3'],
    ['万', 'まん', 'VẠN', 'mười nghìn, vạn', '', 'minano-nihongo-3'],
    ['億', 'おく', 'ỨC', 'một trăm triệu', '', 'minano-nihongo-25'],
    ['番号', 'ばんごう', 'PHIÊN HIỆU', 'Số (số điện thoại, số phòng)', '', 'minano-nihongo-4'],
    ['半', 'はん', 'BÁN', 'Rưỡi, nửa', '', 'minano-nihongo-4'],
    ['半分', 'はんぶん', 'BÁN PHÂN', 'một nửa', 'ケーキを半分に切ります。', 'minano-nihongo-44'],
    ['全部', 'ぜんぶ', 'TOÀN BỘ', 'Toàn bộ, tất cả', '', 'minano-nihongo-24'],
    ['全部で', 'ぜんぶで', 'TOÀN BỘ', 'tổng cộng', '', 'minano-nihongo-11'],
    ['十分', 'じゅうぶん', 'THẬP PHÂN', 'đủ/ đầy đủ', '時間は十分あります。', 'minano-nihongo-32'],
    ['１人', 'ひとり', 'NHÂN', 'một người', '', 'minano-nihongo-11'],
    ['２人', 'ふたり', 'NHÂN', 'hai người', '', 'minano-nihongo-11'],
    ['～人', '～にん', 'NHÂN', '～ người', '', 'minano-nihongo-11'],
    ['～台', '～だい', 'ĐÀI', '～ cái', '', 'minano-nihongo-11'],
    ['～枚', '～まい', 'MAI', '～ tờ, tấm', '', 'minano-nihongo-11'],
    ['～回', '～かい', 'HỒI', '～ lần', '', 'minano-nihongo-11'],
    ['～時間', '～じかん', 'THỜI GIAN', '～ tiếng', '', 'minano-nihongo-11'],
    ['～週間', '～しゅうかん', 'CHU GIAN', '～ tuần', '', 'minano-nihongo-11'],
    ['～か月', '～かげつ', 'NGUYỆT', '～ tháng', '', 'minano-nihongo-11'],
    ['～年', '～ねん', 'NIÊN', '～ năm', '', 'minano-nihongo-11'],
    ['何回も', 'なんかいも', 'HÀ HỒI', 'Nhiều lần', '', 'minano-nihongo-19'],
    ['何階', 'なんがい', 'HÀ GIAI', 'tầng mấy', '', 'minano-nihongo-3'],
    ['何番', 'なんばん', 'HÀ PHIÊN', 'Số bao nhiêu, số mấy', '', 'minano-nihongo-4'],
    ['何歳', 'なんさい', 'HÀ TUẾ', 'Mấy tuổi, bao nhiêu tuổi', '', 'minano-nihongo-1'],
    ['何時', 'なんじ', 'HÀ THỜI', 'Mấy giờ', '', 'minano-nihongo-4'],
    ['何分', 'なんぷん', 'HÀ PHÂN', 'Mấy phút', '', 'minano-nihongo-4'],
    ['量', 'りょう', 'LƯỢNG', 'lượng', 'ご飯の量が多すぎます。', 'minano-nihongo-44'],
    ['大きさ', 'おおきさ', 'ĐẠI', 'cỡ/ kích thước', '部屋の大きさを測ります。', 'minano-nihongo-40'],
    ['長さ', 'ながさ', 'TRƯỜNG', 'chiều dài', '川の長さを調べます。', 'minano-nihongo-40'],
    ['重さ', 'おもさ', 'TRỌNG', 'cân nặng/ trọng lượng', '荷物の重さは10キロです。', 'minano-nihongo-40'],
    ['高さ', 'たかさ', 'CAO', 'chiều cao', '山の高さはどのくらいですか。', 'minano-nihongo-40'],
    ['数えます', 'かぞえます', 'SỐ', 'đếm', '人数を数えてください。', 'minano-nihongo-40'],
    ['測ります', 'はかります', 'TRẮC', 'đo', '部屋の広さを測ります。', 'minano-nihongo-40'],
    ['量ります', 'はかります', 'LƯỢNG', 'cân', '荷物の重さを量ります。', 'minano-nihongo-40'],
    ['確かめます', 'たしかめます', 'XÁC', 'xác nhận/ kiểm tra lại', '予約したかどうか確かめます。', 'minano-nihongo-40'],
    ['はかり', '', '', 'cân (scale)', '', 'soumatome-n3-2'],
    ['はかりで量る', 'はかりではかる', '', 'cân bằng cân (weigh on a scale)', '', 'soumatome-n3-2'],
    ['リットル', '', '', 'lít', '', 'soumatome-n3-2'],
    ['グラム', '', '', 'gam', '', 'soumatome-n3-2'],
    ['カップ', '', '', 'cốc đong', '', 'soumatome-n3-2'],
    ['大さじ', 'おおさじ', '', 'thìa canh (table spoon)', '', 'soumatome-n3-2'],
    ['小さじ', 'こさじ', '', 'thìa cà phê (tea spoon)', '', 'soumatome-n3-2'],
    ['人が多い', 'ひとがおおい', 'NHÂN ĐA', 'Nhiều người', '', 'minano-nihongo-12'],
    ['人が少ない', 'ひとがすくない', 'NHÂN THIỂU', 'Ít người', '', 'minano-nihongo-12'],
    ['少し', 'すこし', 'THIẾU/ THIỂU', 'ít, một ít', '', 'minano-nihongo-9'],
    ['もう少し', 'もうすこし', 'THIẾU', 'Thêm một chút nữa thôi', '', 'minano-nihongo-14'],
    ['全然', 'ぜんぜん', 'TOÀN NHIÊN', 'hoàn toàn ~ không', '', 'minano-nihongo-9'],
    ['大勢', 'おおぜい', 'ĐẠI THẾ', 'nhiều người', '会場に大勢の人が集まりました。', 'minano-nihongo-39'],
    ['輸出が増えます', 'ゆしゅつがふえます', 'THÂU XUẤT TĂNG', 'xuất khẩu tăng lên', '車の輸出が増えています。', 'minano-nihongo-42'],
    ['輸出が減ります', 'ゆしゅつがへります', 'THÂU XUẤT GIẢM', 'xuất khẩu giảm xuống', '今年は輸出が減りました。', 'minano-nihongo-42'],
    ['値段が上がります', 'ねだんがあがります', 'TRỊ ĐOẠN THƯỢNG', 'giá tăng lên', '野菜の値段が上がりました。', 'minano-nihongo-42'],
    ['値段が下がります', 'ねだんがさがります', 'TRỊ ĐOẠN HẠ', 'giá giảm xuống', 'パソコンの値段が下がりました。', 'minano-nihongo-42'],
  ]],
  ['cam-xuc-tinh-cach', [
    ['気持ち', 'きもち', 'KHÍ TRÌ', 'cảm giác/ tâm trạng', '天気がいいと気持ちがいいです。', 'minano-nihongo-36'],
    ['気分がいい', 'きぶんがいい', 'KHÍ PHÂN', 'thấy khỏe/ thấy dễ chịu/ tâm trạng tốt', '今日は気分がいいです。', 'minano-nihongo-26'],
    ['気分が悪い', 'きぶんがわるい', 'KHÍ PHÂN ÁC', 'thấy khó chịu/ thấy mệt/ tâm trạng tệ', '少し気分が悪いです。', 'minano-nihongo-26'],
    ['心', 'こころ', 'TÂM', 'trái tim/ tấm lòng', '心から感謝しています。', 'minano-nihongo-48'],
    ['性格', 'せいかく', 'TÍNH CÁCH', 'tính cách/ tính tình', '明るい性格の人が好きです。', 'minano-nihongo-38'],
    ['夢', 'ゆめ', 'MỘNG', 'giấc mơ/ ước mơ', '昨日の夜、変な夢を見ました。', 'minano-nihongo-27'],
    ['力', 'ちから', 'LỰC', 'sức lực/ năng lực', '力があります。', 'minano-nihongo-28'],
    ['人気', 'にんき', 'NHÂN KHÍ', 'sự hâm mộ/ sự nổi tiếng', 'この歌手は人気があります。', 'minano-nihongo-28'],
    ['興味', 'きょうみ', 'HƯNG VỊ', 'sự quan tâm/ hứng thú', '日本の文化に興味があります。', 'minano-nihongo-41'],
    ['楽しい', 'たのしい', 'LẠC/ NHẠC', 'vui', '', 'minano-nihongo-8'],
    ['楽しみ', 'たのしみ', 'NHẠC', 'niềm vui/ điều mong đợi', '旅行が楽しみです。', 'minano-nihongo-35'],
    ['楽しみます', 'たのしみます', 'LẠC', 'vui/ tận hưởng', 'みんなでパーティーを楽しみました。', 'minano-nihongo-48'],
    ['楽しみにしています', 'たのしみにしています', 'LẠC', 'đang mong đợi/ lấy làm vui', '旅行を楽しみにしています。', 'minano-nihongo-45'],
    ['大好き', 'だいすき', 'ĐẠI HẢO', 'rất thích/ thích lắm', '私は猫が大好きです。', 'minano-nihongo-27'],
    ['悲しい', 'かなしい', 'BI', 'buồn/ đau thương', '悲しいニュースを聞きました。', 'minano-nihongo-39'],
    ['悲しみ', 'かなしみ', 'BI', 'nỗi buồn/ niềm đau', '彼の悲しみは言葉にできません。', 'minano-nihongo-33'],
    ['寂しい', 'さびしい', 'TỊCH', 'buồn, cô đơn', '', 'minano-nihongo-13'],
    ['怖い', 'こわい', 'BỐ', 'sợ/ đáng sợ', '私はお化けが怖いです。', 'minano-nihongo-26'],
    ['恥ずかしい', 'はずかしい', 'SỈ', 'xấu hổ/ thẹn', '間違えて恥ずかしかったです。', 'minano-nihongo-39'],
    ['嫌', 'いや', 'HIỀM', 'chán/ ghét', '嫌なことを忘れます。', 'minano-nihongo-30'],
    ['嫌がります', 'いやがります', 'HIỀM', 'không thích/ tỏ ra ghét', '子どもが薬を嫌がります。', 'minano-nihongo-44'],
    ['幸せ', 'しあわせ', 'HẠNH', 'hạnh phúc', '家族と一緒にいると幸せです。', 'minano-nihongo-42'],
    ['安心します', 'あんしんします', 'AN TÂM', 'yên tâm', '家族が元気だと聞いて安心しました。', 'minano-nihongo-39'],
    ['心配', 'しんぱい', 'TÂM PHỐI', 'lo lắng', '息子のことが心配です。', 'minano-nihongo-32'],
    ['心配します', 'しんぱいします', 'TÂM PHỐI', 'Lo lắng', '', 'minano-nihongo-17'],
    ['困ります', 'こまります', 'KHỐN', 'rắc rối/ khó xử/ gặp khó', '道が分からなくて困りました。', 'minano-nihongo-32'],
    ['困ったなあ', 'こまったなあ', 'KHỐN', 'Khổ quá!/ Làm thế nào đây!/ Biết làm sao bây giờ!', '道に迷って、困ったなあ。', 'minano-nihongo-26'],
    ['悩み', 'なやみ', 'NÃO', 'điều trăn trở/ nỗi phiền muộn', '悩みがあったら、相談してください。', 'minano-nihongo-45'],
    ['緊張します', 'きんちょうします', 'KHẨN TRƯƠNG', 'căng thẳng/ hồi hộp', '発表の前は緊張します。', 'minano-nihongo-50'],
    ['泣きます', 'なきます', 'KHÁP', 'khóc', '赤ちゃんが泣いています。', 'minano-nihongo-44'],
    ['笑います', 'わらいます', 'TIẾU', 'cười', 'みんなで笑いました。', 'minano-nihongo-44'],
    ['涙', 'なみだ', 'LỆ', 'nước mắt', '涙が出ました。', 'minano-nihongo-44'],
    ['親切', 'しんせつ', 'THÂN THIẾT', 'tốt bụng, thân thiện', '', 'minano-nihongo-8'],
    ['優しい', 'やさしい', 'ƯU', 'tình cảm/ hiền lành', '先生はとても優しいです。', 'minano-nihongo-28'],
    ['厳しい', 'きびしい', 'NGHIÊM', 'nghiêm/ nghiêm khắc', '父は厳しい人です。', 'minano-nihongo-48'],
    ['熱心', 'ねっしん', 'NHIỆT TÂM', 'nhiệt tâm/ nhiệt tình/ hết lòng', '彼は仕事に熱心です。', 'minano-nihongo-28'],
    ['一生懸命', 'いっしょうけんめい', 'NHẤT SINH HUYỀN MỆNH', 'chăm chỉ/ miệt mài', '一生懸命練習しました。', 'minano-nihongo-37'],
    ['偉い', 'えらい', 'VĨ', 'vĩ đại/ đáng kính/ đáng khâm phục', '彼は偉い人です。', 'minano-nihongo-28'],
    ['えらい', '', '', 'giỏi/ đáng khen (admirable)', '', 'soumatome-n3-6'],
    ['わがままな', '', '', 'ích kỷ/ đòi hỏi (self-centered)', '', 'soumatome-n3-6'],
    ['生意気な', 'なまいきな', '', 'xấc xược (impertinent)', '', 'soumatome-n3-6'],
    ['利口な', 'りこうな', '', 'khôn/ thông minh (smart)', '', 'soumatome-n3-6'],
    ['かしこい', '', '', 'khôn/ thông minh (smart)', '', 'soumatome-n3-6'],
    ['人なつっこい', 'ひとなつっこい', '', 'dễ gần/ quấn người (friendly)', '', 'soumatome-n3-6'],
    ['かわいらしい', '', '', 'dễ thương (lovely)', '', 'soumatome-n3-6'],
    ['かわいそうな', '', '', 'tội nghiệp (poor)', '', 'soumatome-n3-6'],
    ['行儀がいい', 'ぎょうぎがいい', '', 'ngoan/ lễ phép (well-mannered)', '', 'soumatome-n3-6'],
    ['いたずらな', '', '', 'tinh nghịch (mischievous)', '', 'soumatome-n3-6'],
    ['丁寧', 'ていねい', 'ĐINH NINH', 'lịch sự/ cẩn thận', '丁寧に説明してくださいました。', 'minano-nihongo-44'],
    ['適当', 'てきとう', 'THÍCH ĐƯƠNG', 'thích hợp/ vừa phải', '適当な大きさに切ってください。', 'minano-nihongo-42'],
    ['変', 'へん', 'BIẾN', 'lạ/ kỳ quặc', '変な人に会いました。', 'minano-nihongo-42'],
    ['不思議', 'ふしぎ', 'BẤT TƯ NGHỊ', 'kỳ lạ/ khó tin/ bí ẩn', 'この話はとても不思議です。', 'minano-nihongo-27'],
    ['珍しい', 'めずらしい', 'TRÂN', 'hiếm/ hiếm có', 'これは珍しい切手です。', 'minano-nihongo-35'],
    ['大変', 'たいへん', 'ĐẠI BIẾN', 'vất vả, khó khăn, khổ', '', 'minano-nihongo-13'],
    ['賛成', 'さんせい', 'TÁN THÀNH', 'tán thành/ đồng ý', 'その意見に賛成です。', 'minano-nihongo-47'],
    ['反対', 'はんたい', 'PHẢN ĐỐI', 'phản đối', '父は反対しているようです。', 'minano-nihongo-47'],
    ['意見', 'いけん', 'Ý KIẾN', 'Ý kiến', '', 'minano-nihongo-21'],
    ['感謝します', 'かんしゃします', 'CẢM TẠ', 'cảm ơn/ biết ơn', '皆様に感謝しております。', 'minano-nihongo-50'],
    ['謝ります', 'あやまります', 'TẠ', 'xin lỗi/ tạ lỗi', '遅刻したので、先生に謝りました。', 'minano-nihongo-45'],
    ['褒めます', 'ほめます', 'BAO', 'khen', '先生に褒められました。', 'minano-nihongo-37'],
    ['信じます', 'しんじます', 'TÍN', 'tin/ tin tưởng', '私はその話を信じません。', 'minano-nihongo-45'],
    ['頑張ります', 'がんばります', 'NGOAN TRƯƠNG', 'cố, cố gắng', '', 'minano-nihongo-25'],
  ]],
  ['tu-tha-dong-tu', [
    ['ドアが開きます', 'ドアがあきます', 'KHAI', 'cửa mở ra', '自動でドアが開きます。', 'minano-nihongo-29'],
    ['開けます', 'あけます', 'KHAI', 'Mở', '', 'minano-nihongo-14'],
    ['ドアが閉まります', 'ドアがしまります', 'BẾ', 'cửa đóng lại', '風でドアが閉まりました。', 'minano-nihongo-29'],
    ['閉めます', 'しめます', 'BẾ', 'Đóng', '', 'minano-nihongo-14'],
    ['電気がつきます', 'でんきがつきます', 'ĐIỆN KHÍ', 'điện bật sáng', '部屋の電気がつきます。', 'minano-nihongo-29'],
    ['電気が消えます', 'でんきがきえます', 'ĐIỆN KHÍ TIÊU', 'điện tắt', '急に電気が消えました。', 'minano-nihongo-29'],
    ['消します', 'けします', 'TIÊU', 'Tắt', '', 'minano-nihongo-14'],
    ['いすが壊れます', 'いすがこわれます', 'HOẠI', 'ghế bị hỏng', '古いいすが壊れました。', 'minano-nihongo-29'],
    ['壊します', 'こわします', 'HOẠI', 'phá/ làm hỏng', '弟にカメラを壊されました。', 'minano-nihongo-37'],
    ['コップが割れます', 'コップがわれます', 'CÁT', 'cốc bị vỡ', '落としてコップが割れました。', 'minano-nihongo-29'],
    ['木が折れます', 'きがおれます', 'MỘC TRIẾT', 'cây bị gãy', '台風で木が折れました。', 'minano-nihongo-29'],
    ['折ります', 'おります', 'TRIẾT', 'gấp/ gập/ bẻ', '紙を半分に折ってください。', 'minano-nihongo-34'],
    ['紙が破れます', 'かみがやぶれます', 'CHỈ PHÁ', 'giấy bị rách', 'かばんの中で紙が破れました。', 'minano-nihongo-29'],
    ['服が汚れます', 'ふくがよごれます', 'PHỤC Ô', 'quần áo bị bẩn', '遊んで服が汚れました。', 'minano-nihongo-29'],
    ['汚します', 'よごします', 'Ô', 'làm bẩn', '子どもに服を汚されました。', 'minano-nihongo-37'],
    ['ボタンが外れます', 'ボタンがはずれます', 'NGOẠI', 'cúc bị tuột', 'シャツのボタンが外れました。', 'minano-nihongo-29'],
    ['エレベーターが止まります', 'エレベーターがとまります', 'CHỈ', 'thang máy dừng lại', '地震でエレベーターが止まりました。', 'minano-nihongo-29'],
    ['止めます', 'とめます', 'CHỈ', 'Dừng, đỗ', '', 'minano-nihongo-14'],
    ['落とします', 'おとします', 'LẠC', 'đánh rơi/ làm rơi', '電車で財布を落としました。', 'minano-nihongo-29'],
    ['荷物が落ちます', 'にもつがおちます', 'HÀ VẬT LẠC', 'hành lý bị rơi', '棚から荷物が落ちました。', 'minano-nihongo-42'],
    ['鍵が掛かります', 'かぎがかかります', 'QUẢI', 'cửa được khoá', 'ドアに鍵が掛かっています。', 'minano-nihongo-29'],
    ['かぎを掛けます', 'かぎをかけます', 'QUẢI', 'khóa/ khóa bằng chìa', '出かけるとき、かぎを掛けるのを忘れないでください。', 'minano-nihongo-38'],
    ['荷物が片付きます', 'にもつがかたづきます', 'HÀ VẬT PHIẾN PHÓ', 'đồ đạc được dọn gọn/ đồ đạc được sắp xếp ngăn nắp', '荷物が片付きました。', 'minano-nihongo-26'],
    ['片づけます', 'かたづけます', 'PHIẾN', 'dọn dẹp/ sắp xếp', '部屋を片づけます。', 'minano-nihongo-30'],
    ['始めます', 'はじめます', 'THỦY', 'Bắt đầu', '', 'minano-nihongo-14'],
    ['式が始まります', 'しきがはじまります', 'THỨC THỦY', 'bắt đầu buổi lễ', 'もうすぐ式が始まります。', 'minano-nihongo-31'],
    ['続けます', 'つづけます', 'TỤC', 'tiếp tục', '日本語の勉強を続けます。', 'minano-nihongo-31'],
    ['熱が続きます', 'ねつがつづきます', 'NHIỆT TỤC', 'sốt kéo dài/ vẫn còn sốt', '三日も熱が続いています。', 'minano-nihongo-32'],
    ['戻します', 'もどします', 'LỆ', 'trả về/ để lại vị trí ban đầu', '本を元の場所に戻します。', 'minano-nihongo-30'],
    ['戻ります', 'もどります', 'LỆ', 'quay lại/ trở lại', '3時までに会社に戻ります。', 'minano-nihongo-32'],
    ['入れます', 'いれます', 'NHẬP', 'Cho vào, bỏ vào', '', 'minano-nihongo-16'],
    ['出します', 'だします', 'XUẤT', 'Lấy ra, rút (tiền)', '', 'minano-nihongo-16'],
    ['集めます', 'あつめます', 'TẬP', 'Sưu tầm, thu thập', '', 'minano-nihongo-18'],
    ['人が集まります', 'ひとがあつまります', 'NHÂN TẬP', 'người tụ tập/ mọi người tập trung', '会場に人が集まっているようです。', 'minano-nihongo-47'],
    ['見つけます', 'みつけます', 'KIẾN', 'tìm/ tìm thấy', 'いい仕事を見つけました。', 'minano-nihongo-31'],
    ['かぎが見つかります', 'かぎがみつかります', 'KIẾN', 'tìm thấy chìa khóa', 'なくしたかぎが見つかりました。', 'minano-nihongo-34'],
    ['直します', 'なおします', 'TRỰC', 'Sửa, chữa', '', 'minano-nihongo-20'],
    ['故障が直ります', 'こしょうがなおります', 'CỐ CHƯỚNG TRỰC', 'chỗ hỏng được sửa/ hết hỏng', '車の故障がやっと直りました。', 'minano-nihongo-32'],
    ['病気が治ります', 'びょうきがなおります', 'BỆNH KHÍ TRỊ', 'khỏi bệnh/ bệnh khỏi', '薬を飲んだら、病気が治りました。', 'minano-nihongo-32'],
    ['色が変わります', 'いろがかわります', 'SẮC PHẢN', 'đổi màu/ thay đổi màu', '秋になると、葉の色が変わります。', 'minano-nihongo-35'],
    ['変えます', 'かえます', 'BIẾN', 'Đổi', '', 'minano-nihongo-23'],
    ['動かします', 'うごかします', 'ĐỘNG', 'làm dịch chuyển/ khởi động', '机を動かしてもいいですか。', 'minano-nihongo-40'],
    ['時計が動きます', 'とけいがうごきます', 'THỜI KẾ ĐỘNG', 'Chuyển động, chạy đồng hồ', '', 'minano-nihongo-23'],
    ['倒れます', 'たおれます', 'ĐẢO', 'đổ/ ngã', '地震で本棚が倒れました。', 'minano-nihongo-29'],
    ['ビルが倒れます', 'ビルがたおれます', 'ĐẢO', 'nhà cao tầng bị đổ', '地震でビルが倒れました。', 'minano-nihongo-39'],
    ['焼きます', 'やきます', 'THIÊU', 'nướng/ rán', '魚を焼いているところです。', 'minano-nihongo-46'],
    ['肉が焼けます', 'にくがやけます', 'NHỤC THIÊU', 'thịt được nướng chín', '肉が焼けたら、食べましょう。', 'minano-nihongo-39'],
    ['煮ます', 'にます', 'CHỬ', 'nấu/ hầm', '野菜を弱火で煮ます。', 'minano-nihongo-34'],
    ['煮えます', 'にえます', 'CHỬ', 'chín/ được nấu chín', '野菜が煮えたら、火を止めてください。', 'minano-nihongo-34'],
    ['上げます', 'あげます', 'THƯỢNG', 'nâng lên/ giơ lên/ tăng lên', 'わかる人は手を上げてください。', 'minano-nihongo-33'],
    ['値段が上がります', 'ねだんがあがります', 'TRỊ ĐOẠN THƯỢNG', 'giá tăng lên', '野菜の値段が上がりました。', 'minano-nihongo-42'],
    ['下げます', 'さげます', 'HẠ', 'hạ xuống/ giảm xuống/ hạ', 'エアコンの温度を下げましょう。', 'minano-nihongo-33'],
    ['値段が下がります', 'ねだんがさがります', 'TRỊ ĐOẠN HẠ', 'giá giảm xuống', 'パソコンの値段が下がりました。', 'minano-nihongo-42'],
    ['輸出が増えます', 'ゆしゅつがふえます', 'THÂU XUẤT TĂNG', 'xuất khẩu tăng lên', '車の輸出が増えています。', 'minano-nihongo-42'],
    ['輸出が減ります', 'ゆしゅつがへります', 'THÂU XUẤT GIẢM', 'xuất khẩu giảm xuống', '今年は輸出が減りました。', 'minano-nihongo-42'],
    ['ひもが切れます', 'ひもがきれます', 'THIẾT', 'sợi dây bị đứt', '荷物のひもが切れました。', 'minano-nihongo-42'],
    ['売ります', 'うります', 'MẠI', 'Bán', '', 'minano-nihongo-15'],
    ['売れます', 'うれます', 'MẠI', 'bán chạy/ được bán', 'このパンはよく売れます。', 'minano-nihongo-28'],
    ['ジュースをこぼす', '', '', 'làm đổ nước ngọt (spill the juice)', '', 'soumatome-n3-4'],
    ['ジュースがこぼれる', '', '', 'nước ngọt bị đổ (the juice is spilled)', '', 'soumatome-n3-4'],
    ['部屋を散らかす', 'へやをちらかす', '', 'bày bừa phòng (clutter the room)', '', 'soumatome-n3-4'],
    ['部屋が散らかる', 'へやがちらかる', '', 'phòng bừa bộn (the room is cluttered)', '', 'soumatome-n3-4'],
    ['部屋を片づける', 'へやをかたづける', '', 'dọn phòng (tidy up the room)', '', 'soumatome-n3-4'],
    ['部屋が片づく', 'へやがかたづく', '', 'phòng đã gọn (the room is tidied)', '', 'soumatome-n3-4'],
    ['（お）湯を沸かす', 'ゆをわかす', '', 'đun sôi nước (boil the water)', '', 'soumatome-n3-3'],
    ['（お）湯が沸く', 'ゆがわく', '', 'nước sôi', '', 'soumatome-n3-3'],
    ['（お）湯を冷ます', 'ゆをさます', '', 'để nguội nước nóng (let hot water cool)', '', 'soumatome-n3-3'],
    ['（お）湯が冷める', 'ゆがさめる', '', 'nước nguội đi', '', 'soumatome-n3-3'],
    ['ぬらす', '', '', 'làm ướt (wet)', '', 'soumatome-n3-5'],
    ['ぬれている', '', '', 'đang ướt (wet)', '', 'soumatome-n3-5'],
    ['乾く', 'かわく', '', 'khô (dry)', '', 'soumatome-n3-5'],
    ['乾燥機で乾かす', 'かんそうきでかわかす', '', 'sấy bằng máy sấy (dry in the dryer)', '', 'soumatome-n3-5'],
    ['しわを伸ばす', 'しわをのばす', '', 'vuốt phẳng nếp nhăn (take the creases out)', '', 'soumatome-n3-5'],
    ['しわが伸びる', 'しわがのびる', '', 'nếp nhăn đã phẳng (the creases have been smoothed out)', '', 'soumatome-n3-5'],
  ]],
  ['trang-tu-cach-noi', [
    ['少し', 'すこし', 'THIẾU/ THIỂU', 'ít, một ít', '', 'minano-nihongo-9'],
    ['もう少し', 'もうすこし', 'THIẾU', 'Thêm một chút nữa thôi', '', 'minano-nihongo-14'],
    ['全然', 'ぜんぜん', 'TOÀN NHIÊN', 'hoàn toàn ~ không', '', 'minano-nihongo-9'],
    ['時々', 'ときどき', 'THÌ KÉP', 'thỉnh thoảng', '', 'minano-nihongo-6'],
    ['特に', 'とくに', 'ĐẶC', 'Đặc biệt', '', 'minano-nihongo-15'],
    ['直接', 'ちょくせつ', 'TRỰC TIẾP', 'trực tiếp', '社長と直接話します。', 'minano-nihongo-26'],
    ['何でも', 'なんでも', 'HÀ', 'cái gì cũng/ bất cứ thứ gì', '何でも食べられます。', 'minano-nihongo-26'],
    ['何か', 'なにか', 'HÀ', 'cái gì đó', '', 'minano-nihongo-13'],
    ['自分', 'じぶん', 'TỰ PHÂN', 'bản thân/ mình/ tự mình', '自分一人でやります。', 'minano-nihongo-27'],
    ['自分で', 'じぶんで', 'BỘ PHÂN', 'Tự mình', '', 'minano-nihongo-24'],
    ['別々に', 'べつべつに', 'BIỆT', 'riêng ra/ để riêng', '', 'minano-nihongo-13'],
    ['別の', 'べつの', 'BIỆT', 'khác/ một cái khác', '別の日に会いましょう。', 'minano-nihongo-26'],
    ['次の', 'つぎの', 'THỨ', 'tiếp theo', '', 'minano-nihongo-5'],
    ['次に', 'つぎに', 'THỨ', 'Tiếp theo', '', 'minano-nihongo-16'],
    ['先に', 'さきに', 'TIÊN', 'trước', '私が先に行きます。', 'minano-nihongo-34'],
    ['例えば', 'たとえば', 'LỆ', 'ví dụ như/ chẳng hạn/ ví dụ', '例えば、この問題を見てください。', 'minano-nihongo-27'],
    ['実は', 'じつは', 'THỰC', 'Thật ra là/ sự tình là', '', 'minano-nihongo-19'],
    ['必ず', 'かならず', 'TẤT', 'nhất định/ chắc chắn', '必ず連絡してください。', 'minano-nihongo-36'],
    ['絶対に', 'ぜったいに', 'TUYỆT ĐỐI', 'tuyệt đối/ nhất định', '絶対に忘れないようにします。', 'minano-nihongo-36'],
    ['急に', 'きゅうに', 'CẤP', 'đột nhiên/ gấp', '急に雨が降ってきました。', 'minano-nihongo-40'],
    ['今にも', 'いまにも', 'KIM', 'sắp/ chỉ chực', '今にも雨が降りそうな空です。', 'minano-nihongo-42'],
    ['今でも', 'いまでも', 'KIM', 'ngay cả bây giờ', '今でもよく覚えています。', 'minano-nihongo-40'],
    ['今では', 'いまでは', 'KIM', 'bây giờ thì', '今では日本の生活に慣れました。', 'minano-nihongo-39'],
    ['たった今', 'たったいま', 'KIM', 'vừa mới rồi', 'たった今着いたところです。', 'minano-nihongo-46'],
    ['初めて', 'はじめて', 'SƠ', 'Lần đầu tiên', '', 'minano-nihongo-12'],
    ['何回も', 'なんかいも', 'HÀ HỒI', 'Nhiều lần', '', 'minano-nihongo-19'],
    ['一生懸命', 'いっしょうけんめい', 'NHẤT SINH HUYỀN MỆNH', 'chăm chỉ/ miệt mài', '一生懸命練習しました。', 'minano-nihongo-37'],
    ['自由に', 'じゆうに', 'TỰ DO', 'tự do/ tuỳ thích/ thoải mái', 'ここで自由に写真を撮ることができます。', 'minano-nihongo-27'],
    ['遠慮なく', 'えんりょなく', 'VIỄN LỰ', 'đừng khách sáo/ không làm khách', 'どうぞ遠慮なく召し上がってください。', 'minano-nihongo-49'],
    ['楽しく', 'たのしく', 'LẠC', 'vui/ vui vẻ', 'みんなで楽しく歌いました。', 'minano-nihongo-41'],
    ['短く', 'みじかく', 'ĐOẢN', 'ngắn/ ngắn gọn', '短く説明してください。', 'minano-nihongo-33'],
    ['早く', 'はやく', 'TẢO', 'sớm, nhanh', '', 'minano-nihongo-9'],
    ['速く', 'はやく', 'TỐC', 'sớm, nhanh', '', 'minano-nihongo-9'],
    ['遅く', 'おそく', 'TRÌ', 'muộn/ khuya', '昨夜は遅くまで働きました。', 'minano-nihongo-32'],
    ['上手に', 'じょうずに', 'THƯỢNG THỦ', 'giỏi/ khéo', '日本語が上手に話せるようになりたいです。', 'minano-nihongo-36'],
    ['確か', 'たしか', 'XÁC', 'nếu không lầm thì', '確か来週だったと思います。', 'minano-nihongo-29'],
    ['途中で', 'とちゅうで', 'ĐỒ TRUNG', 'giữa đường/ dọc đường', '学校へ行く途中で友達に会いました。', 'minano-nihongo-39'],
    ['帰りに', 'かえりに', 'QUY', 'trên đường về', '帰りに買い物をします。', 'minano-nihongo-49'],
    ['大丈夫', 'だいじょうぶ', 'ĐẠI TRƯỢNG PHU', 'Không sao, không có vấn đề gì', '', 'minano-nihongo-17'],
    ['無理', 'むり', 'VÔ LÝ', 'Không thể, quá sức', '', 'minano-nihongo-19'],
    ['十分', 'じゅうぶん', 'THẬP PHÂN', 'đủ/ đầy đủ', '時間は十分あります。', 'minano-nihongo-32'],
    ['理由', 'りゆう', 'LÝ DO', 'lý do', '遅れた理由を説明します。', 'minano-nihongo-44'],
    ['順序', 'じゅんじょ', 'THUẬN TỰ', 'thứ tự', '順序を間違えました。', 'minano-nihongo-44'],
    ['表現', 'ひょうげん', 'BIỂU HIỆN', 'cách nói/ cách diễn đạt', 'この表現は使いにくいです。', 'minano-nihongo-44'],
    ['方法', 'ほうほう', 'PHƯƠNG PHÁP', 'phương pháp/ cách làm', 'もっといい方法を考えましょう。', 'minano-nihongo-35'],
    ['様子', 'ようす', 'DẠNG TỬ', 'vẻ/ tình hình', '外の様子を見てきます。', 'minano-nihongo-40'],
    ['原因', 'げんいん', 'NGUYÊN NHÂN', 'nguyên nhân', '事故の原因を調べています。', 'minano-nihongo-46'],
    ['中止', 'ちゅうし', 'TRUNG CHỈ', 'dừng/ đình chỉ', '雨の場合は中止します。', 'minano-nihongo-45'],
    ['以上です', 'いじょうです', 'DĨ THƯỢNG', 'Trên đây là hết./ Tôi xin hết.', '説明は以上です。', 'minano-nihongo-45'],
  ]],
  ['chao-hoi-kinh-ngu', [
    ['お帰りなさい。', 'おかえりなさい', 'QUY', 'Anh/Chị đã về đấy à.', '', 'minano-nihongo-12'],
    ['お先にどうぞ', 'おさきにどうぞ', 'TIÊN', 'Xin mời anh/chị đi trước.', 'エレベーターで「お先にどうぞ」と言います。', 'minano-nihongo-29'],
    ['お先に失礼します', 'おさきにしつれいします', 'TIÊN THẤT LỄ', 'Tôi xin phép về trước.', '用事があるので、お先に失礼します。', 'minano-nihongo-38'],
    ['お疲れ様でした', 'おつかれさまでした', 'BÌ DẠNG', 'Anh/chị đã vất vả rồi.', '今日もお疲れ様でした。', 'minano-nihongo-39'],
    ['申し訳ありません', 'もうしわけありません', 'THÂN DỊCH', 'Xin lỗi/ Thành thật xin lỗi.', 'お待たせして申し訳ありません。', 'minano-nihongo-41'],
    ['失礼いたします', 'しつれいいたします', 'THẤT LỄ', 'Tôi xin phép.', 'では、失礼いたします。', 'minano-nihongo-49'],
    ['よろしくお伝えください', 'よろしくおつたえください', 'TRUYỀN', 'Cho tôi gửi lời hỏi thăm.', '奥様によろしくお伝えください。', 'minano-nihongo-49'],
    ['お待たせしました', 'おまたせしました', 'ĐÃI', 'Xin lỗi vì để anh/chị phải đợi.', 'お待たせしました。どうぞ。', 'minano-nihongo-46'],
    ['いろいろお世話になりました。', 'いろいろおせわになりました', 'THẾ THOẠI', 'Anh/chị đã giúp tôi nhiều.', '', 'minano-nihongo-25'],
    ['どうぞお元気で。', 'どうぞおげんきで', 'NGUYÊN KHÍ', 'Chúc anh/chị mạnh khỏe.', '', 'minano-nihongo-25'],
    ['ちょっとお願いがあるんですが', 'ちょっとおねがいがあるんですが', 'NGUYỆN', 'Tôi có chút việc muốn nhờ anh chị.', 'ちょっとお願いがあるんですが、いいですか。', 'minano-nihongo-28'],
    ['これでお願いします。', 'これでおねがいします', 'NGUYỆN', 'Gởi anh tiền này.', '', 'minano-nihongo-14'],
    ['ご注文は？', 'ごちゅうもん', 'CHÚ VĂN', 'anh/chị dùng món gì ạ', '', 'minano-nihongo-13'],
    ['少々お待ちください。', 'しょうしょうおまちください', 'THIỂU ĐÃI', 'xin anh/chị vui lòng đợi một chút', '', 'minano-nihongo-13'],
    ['国へ帰るの？', 'くにへかえるの？', 'QUỐC QUY', 'Anh/chị có về nước không?', '', 'minano-nihongo-20'],
    ['覚えていません', 'おぼえていません', 'GIÁC', 'Tôi không nhớ.', 'その人の名前は覚えていません。', 'minano-nihongo-29'],
    ['今いいでしょうか', 'いまいいでしょうか', 'KIM', 'Bây giờ có được không ạ?', '課長、今いいでしょうか。', 'minano-nihongo-46'],
    ['どちら様でしょうか', 'どちらさまでしょうか', 'DẠNG', 'Ai đấy ạ?', '失礼ですが、どちら様でしょうか。', 'minano-nihongo-46'],
    ['お忙しいですか', 'おいそがしいですか', 'MANG', 'Anh/chị có bận không?', '今、お忙しいですか。', 'minano-nihongo-48'],
    ['お元気でいらっしゃいますか', 'おげんきでいらっしゃいますか', 'NGUYÊN KHÍ', 'Anh/chị có khỏe không ạ?', '皆様、お元気でいらっしゃいますか。', 'minano-nihongo-50'],
    ['拝啓', 'はいけい', 'BÁI KHẢI', 'Kính gửi (mở đầu thư)', '手紙は「拝啓」で始めます。', 'minano-nihongo-50'],
    ['敬具', 'けいぐ', 'KÍNH CỤ', 'Kính thư (kết thúc thư)', '手紙の最後に「敬具」と書きます。', 'minano-nihongo-50'],
    ['困ったなあ', 'こまったなあ', 'KHỐN', 'Khổ quá!/ Làm thế nào đây!/ Biết làm sao bây giờ!', '道に迷って、困ったなあ。', 'minano-nihongo-26'],
    ['乾杯', 'かんぱい', 'CAN BỘI', 'Nâng cốc!/cạn chén', '', 'minano-nihongo-19'],
    ['久しぶり', 'ひさしぶり', 'CỬU', 'lâu rồi (mới gặp lại)', '久しぶりに友達に会いました。', 'minano-nihongo-48'],
    ['迷惑をかけます', 'めいわくをかけます', 'MÊ HOẶC', 'làm phiền', 'ご迷惑をかけて申し訳ありません。', 'minano-nihongo-50'],
    ['遠慮なく', 'えんりょなく', 'VIỄN LỰ', 'đừng khách sáo/ không làm khách', 'どうぞ遠慮なく召し上がってください。', 'minano-nihongo-49'],
    ['お礼', 'おれい', 'LỄ', 'lời cảm ơn/ sự cảm ơn', 'お礼の手紙を書きました。', 'minano-nihongo-50'],
    ['返事', 'へんじ', 'PHẢN SỰ', 'hồi âm/ trả lời', 'まだ返事が来ません。', 'minano-nihongo-40'],
    ['召し上がります', 'めしあがります', 'TRIỆU THƯỢNG', 'ăn/ uống (kính ngữ)', '何を召し上がりますか。', 'minano-nihongo-49'],
    ['ご覧になります', 'ごらんになります', 'LÃM', 'xem/ nhìn (kính ngữ)', 'この写真をご覧になりましたか。', 'minano-nihongo-49'],
    ['ご存じです', 'ごぞんじです', 'TỒN', 'biết (kính ngữ)', '社長の電話番号をご存じですか。', 'minano-nihongo-49'],
    ['お持ちです', 'おもちです', 'TRÌ', 'có (kính ngữ)', '保険証をお持ちですか。', 'minano-nihongo-49'],
    ['参ります', 'まいります', 'THAM', 'đi/ đến (khiêm nhường ngữ)', '明日、10時に参ります。', 'minano-nihongo-50'],
    ['申します', 'もうします', 'THÂN', 'nói/ tên là (khiêm nhường ngữ)', '山田と申します。', 'minano-nihongo-50'],
    ['拝見します', 'はいけんします', 'BÁI KIẾN', 'xem/ nhìn (khiêm nhường ngữ)', 'お手紙を拝見しました。', 'minano-nihongo-50'],
    ['存じます', 'ぞんじます', 'TỒN', 'biết (khiêm nhường ngữ)', 'お名前は存じております。', 'minano-nihongo-50'],
    ['伺います', 'うかがいます', 'TỨ', 'hỏi/ nghe/ đến thăm (khiêm nhường ngữ)', 'ちょっと伺いたいことがあります。', 'minano-nihongo-50'],
    ['お目にかかります', 'おめにかかります', 'MỤC', 'gặp (khiêm nhường ngữ)', '社長にお目にかかりたいのですが。', 'minano-nihongo-50'],
    ['私', 'わたくし', 'TƯ', 'tôi (cách nói lịch sự)', '私はミラーと申します。', 'minano-nihongo-50'],
    ['お宅', 'おたく', 'TRẠCH', 'nhà (của người khác)', '先生のお宅へ伺いました。', 'minano-nihongo-50'],
  ]],
];
