/**
 * DANH SÁCH 214 BỘ THỦ (bảng Khang Hy) — nguồn DUY NHẤT của khu "Bộ thủ".
 *
 * Mỗi dòng là `chữ[/biến thể]|ÂM HÁN VIỆT|nghĩa tiếng Việt|tên tiếng Nhật`.
 * Xếp theo SỐ NÉT, đúng thứ tự bảng Khang Hy — khoá của `RADICAL_ROWS` chính là
 * số nét, nên không phải khai lại số nét trên từng dòng.
 *
 * Biến thể (亻 của 人, 氵 của 水…) ngăn với chữ chính bằng `/`. Đây là phần quan
 * trọng nhất của bảng: chữ Hán ghép bằng BIẾN THỂ chứ hiếm khi bằng dạng gốc, nên
 * thiếu biến thể là bộ đó gom được rất ít chữ.
 *
 * Chữ đứng trước `/` là dạng dùng trong tiếng Nhật hiện đại khi nó khác dạng phồn
 * thể (戸/戶, 麦/麥, 歯/齒…): người học ở đây đang học chữ Nhật.
 *
 * Sửa bảng này thì chạy lại `npm run generate:radicals`.
 */

/** Số nét → các bộ thủ có số nét đó. */
export const RADICAL_ROWS: Readonly<Record<number, readonly string[]>> = {
  1: [
    '一|NHẤT|một|いち',
    '丨|CỔN|nét sổ|たてぼう',
    '丶|CHỦ|dấu chấm|てん',
    '丿|PHIỆT|nét phẩy|の',
    '乙/乚|ẤT|can Ất, cong queo|おつ・おつにょう',
    '亅|QUYẾT|nét móc|はねぼう',
  ],
  2: [
    '二|NHỊ|hai|に',
    '亠|ĐẦU|phần đầu, cái nắp|なべぶた',
    '人/亻|NHÂN|người|ひと・にんべん',
    '儿|NHÂN|người (dạng hai chân)|ひとあし',
    '入|NHẬP|vào|いる',
    '八|BÁT|tám, chia ra|はち',
    '冂|QUYNH|vùng ngoài, bao ngoài|まきがまえ',
    '冖|MỊCH|trùm khăn lên|わかんむり',
    '冫|BĂNG|nước đá|にすい',
    '几|KỶ|cái ghế nhỏ|つくえ',
    '凵|KHẢM|há miệng, cái hố|うけばこ',
    '刀/刂|ĐAO|con dao|かたな・りっとう',
    '力|LỰC|sức mạnh|ちから',
    '勹|BAO|bao bọc|つつみがまえ',
    '匕|CHỦY|cái thìa|さじのひ',
    '匚|PHƯƠNG|cái hộp vuông|はこがまえ',
    '匸|HỆ|che đậy|かくしがまえ',
    '十|THẬP|mười|じゅう',
    '卜|BỐC|xem bói|ぼく・うらない',
    '卩/㔾|TIẾT|đốt tre, con dấu|ふしづくり',
    '厂|HÁN|sườn núi, mái đá|がんだれ',
    '厶|KHƯ|riêng tư|む',
    '又|HỰU|lại nữa, bàn tay phải|また',
  ],
  3: [
    '口|KHẨU|cái miệng|くち',
    '囗|VI|vây quanh|くにがまえ',
    '土|THỔ|đất|つち',
    '士|SĨ|kẻ sĩ|さむらい',
    '夂|TRI|đến, dấu chân|ふゆがしら',
    '夊|TUY|đi chậm|すいにょう',
    '夕|TỊCH|buổi tối|ゆうべ',
    '大|ĐẠI|to lớn|だい',
    '女|NỮ|đàn bà|おんな',
    '子|TỬ|con, trẻ nhỏ|こ',
    '宀|MIÊN|mái nhà|うかんむり',
    '寸|THỐN|tấc, đơn vị đo|すん',
    '小/⺌|TIỂU|nhỏ|しょう',
    '尢|UÔNG|què chân|まげあし',
    '尸|THI|xác chết, thân người|しかばね',
    '屮|TRIỆT|mầm cây|てつ',
    '山|SƠN|núi|やま',
    '巛/川|XUYÊN|sông ngòi|かわ',
    '工|CÔNG|người thợ, công việc|たくみ',
    '己|KỶ|bản thân mình|おのれ',
    '巾|CÂN|cái khăn|はば・きんべん',
    '干|CAN|cái chài, can dự|かん・ほす',
    '幺|YÊU|nhỏ bé|いとがしら',
    '广|NGHIỄM|mái nhà lớn|まだれ',
    '廴|DẪN|bước dài|えんにょう',
    '廾|CỦNG|chắp hai tay|にじゅうあし',
    '弋|DẶC|bắn, cọc buộc|しきがまえ',
    '弓|CUNG|cái cung|ゆみ',
    '彐/彑|KỆ|đầu con nhím|けいがしら',
    '彡|SAM|lông tóc dài|さんづくり',
    '彳|XÍCH|bước chân trái|ぎょうにんべん',
  ],
  4: [
    '心/忄|TÂM|trái tim|こころ・りっしんべん',
    '戈|QUA|cây giáo|ほこ',
    '戸/戶|HỘ|cửa một cánh|とだれ',
    '手/扌|THỦ|bàn tay|て・てへん',
    '支|CHI|cành nhánh|しにょう',
    '攴/攵|PHỘC|đánh khẽ|のぶん',
    '文|VĂN|văn vẻ, chữ viết|ぶん',
    '斗|ĐẨU|cái đấu đong|とます',
    '斤|CÂN|cái rìu, cân nặng|おのづくり',
    '方|PHƯƠNG|vuông, phương hướng|ほう・かたへん',
    '无/旡|VÔ|không có|むにょう',
    '日|NHẬT|mặt trời, ngày|ひ',
    '曰|VIẾT|nói rằng|ひらび',
    '月|NGUYỆT|mặt trăng, tháng|つき',
    '木|MỘC|cây gỗ|き',
    '欠|KHIẾM|thiếu, há miệng|あくび',
    '止|CHỈ|dừng lại|とめる',
    '歹|ĐÁI|xương tàn, chết chóc|がつへん',
    '殳|THÙ|binh khí dài|るまた',
    '毋|VÔ|chớ, đừng|なかれ',
    '比|TỶ|so sánh|くらべる',
    '毛|MAO|lông|け',
    '氏|THỊ|họ tộc|うじ',
    '气|KHÍ|hơi, khí|きがまえ',
    '水/氵|THỦY|nước|みず・さんずい',
    '火/灬|HỎA|lửa|ひ・れっか',
    '爪/爫|TRẢO|móng vuốt|つめ',
    '父|PHỤ|người cha|ちち',
    '爻|HÀO|hào âm dương|こう',
    '爿|TƯỜNG|mảnh gỗ bên trái|しょうへん',
    '片|PHIẾN|mảnh, tấm|かた',
    '牙|NHA|răng nanh|きば',
    '牛/牜|NGƯU|con trâu bò|うし・うしへん',
    '犬/犭|KHUYỂN|con chó|いぬ・けものへん',
  ],
  5: [
    '玄|HUYỀN|đen huyền, sâu kín|げん',
    '玉/王|NGỌC|đá quý|たま・おうへん',
    '瓜|QUA|quả dưa|うり',
    '瓦|NGÕA|ngói|かわら',
    '甘|CAM|ngọt|あまい',
    '生|SINH|sinh ra, sống|うまれる',
    '用|DỤNG|dùng|もちいる',
    '田|ĐIỀN|ruộng|た',
    '疋|THẤT|tấm vải, bàn chân|ひき',
    '疒|NẠCH|bệnh tật|やまいだれ',
    '癶|BÁT|hai chân dang ra|はつがしら',
    '白|BẠCH|màu trắng|しろ',
    '皮|BÌ|da|けがわ',
    '皿|MÃNH|bát đĩa|さら',
    '目|MỤC|con mắt|め',
    '矛|MÂU|cây mâu|ほこ',
    '矢|THỈ|mũi tên|や',
    '石|THẠCH|đá|いし',
    '示/礻|THỊ|chỉ bảo, thần linh|しめす・しめすへん',
    '禸|NHỰU|vết chân thú|ぐうのあし',
    '禾|HÒA|cây lúa|のぎへん',
    '穴|HUYỆT|hang lỗ|あな',
    '立|LẬP|đứng|たつ',
  ],
  6: [
    '竹|TRÚC|cây tre|たけ',
    '米|MỄ|gạo|こめ',
    '糸|MỊCH|sợi tơ|いと',
    '缶|PHẪU|đồ sành, cái lon|ほとぎ',
    '网/罒|VÕNG|cái lưới|あみがしら',
    '羊|DƯƠNG|con dê cừu|ひつじ',
    '羽|VŨ|lông vũ|はね',
    '老/耂|LÃO|già|おいかんむり',
    '而|NHI|mà, bộ râu|しかして',
    '耒|LỖI|cái cày|らいすき',
    '耳|NHĨ|cái tai|みみ',
    '聿|DUẬT|cây bút|ふでづくり',
    '肉/⺼|NHỤC|thịt|にく・にくづき',
    '臣|THẦN|bề tôi|しん',
    '自|TỰ|tự mình, cái mũi|みずから',
    '至|CHÍ|đến nơi|いたる',
    '臼|CỮU|cái cối|うす',
    '舌|THIỆT|cái lưỡi|した',
    '舛|SUYỄN|ngang trái|ます',
    '舟|CHU|con thuyền|ふね',
    '艮|CẤN|quẻ Cấn, bền lại|うしとら',
    '色|SẮC|màu sắc|いろ',
    '艸/艹|THẢO|cỏ|くさかんむり',
    '虍|HÔ|vằn con hổ|とらかんむり',
    '虫|TRÙNG|sâu bọ|むし',
    '血|HUYẾT|máu|ち',
    '行|HÀNH|đi, hàng lối|ぎょうがまえ',
    '衣/衤|Y|áo|ころも・ころもへん',
    '襾/西|Á|che đậy, phía tây|にし',
  ],
  7: [
    '見|KIẾN|nhìn thấy|みる',
    '角|GIÁC|góc, cái sừng|つの',
    '言|NGÔN|lời nói|ことば・ごんべん',
    '谷|CỐC|thung lũng|たに',
    '豆|ĐẬU|hạt đậu|まめ',
    '豕|THỈ|con lợn|いのこ',
    '豸|TRĨ|loài sâu không chân|むじな',
    '貝|BỐI|vỏ sò, tiền của|かい・かいへん',
    '赤|XÍCH|màu đỏ|あか',
    '走|TẨU|chạy|はしる',
    '足|TÚC|bàn chân, đầy đủ|あし',
    '身|THÂN|thân mình|み',
    '車|XA|cái xe|くるま',
    '辛|TÂN|cay, vất vả|からい',
    '辰|THÌN|chi Thìn, buổi sớm|しんのたつ',
    '辵/辶|SƯỚC|bước đi|しんにょう',
    '邑/阝|ẤP|làng xóm|おおざと',
    '酉|DẬU|chi Dậu, hũ rượu|とりへん',
    '釆|BIỆN|phân biệt|のごめ',
    '里|LÝ|dặm, làng xóm|さと',
  ],
  8: [
    '金|KIM|vàng, kim loại|かね・かねへん',
    '長|TRƯỜNG|dài, lớn lên|ながい',
    '門|MÔN|cửa hai cánh|もん',
    '阜/阝|PHỤ|gò đất|こざとへん',
    '隶|ĐÃI|kịp, bắt kịp|れいづくり',
    '隹|CHUY|chim đuôi ngắn|ふるとり',
    '雨|VŨ|mưa|あめ',
    '青/靑|THANH|màu xanh|あお',
    '非|PHI|không phải|あらず',
  ],
  9: [
    '面|DIỆN|khuôn mặt|めん',
    '革|CÁCH|da thuộc, đổi mới|かくのかわ',
    '韋|VI|da mềm|なめしがわ',
    '韭|CỬU|rau hẹ|にら',
    '音|ÂM|âm thanh|おと',
    '頁|HIỆT|cái đầu, trang giấy|おおがい',
    '風|PHONG|gió|かぜ',
    '飛|PHI|bay|とぶ',
    '食/飠|THỰC|ăn|しょく・しょくへん',
    '首|THỦ|cái đầu|くび',
    '香|HƯƠNG|mùi thơm|かおり',
  ],
  10: [
    '馬|MÃ|con ngựa|うま',
    '骨|CỐT|xương|ほね',
    '高|CAO|cao|たかい',
    '髟|TIÊU|tóc dài|かみがしら',
    '鬥|ĐẤU|đánh nhau|とうがまえ',
    '鬯|SƯỞNG|rượu nếp|ちょう',
    '鬲|CÁCH|cái đỉnh|かく',
    '鬼|QUỶ|con quỷ|おに',
  ],
  11: [
    '魚|NGƯ|con cá|うお・さかな',
    '鳥|ĐIỂU|con chim|とり',
    '鹵|LỖ|đất mặn|ろ',
    '鹿|LỘC|con hươu|しか',
    '麦/麥|MẠCH|lúa mạch|むぎ',
    '麻|MA|cây gai|あさ',
  ],
  12: [
    '黄/黃|HOÀNG|màu vàng|き',
    '黍|THỬ|lúa nếp|きび',
    '黒/黑|HẮC|màu đen|くろ',
    '黹|CHỈ|may vá thêu thùa|ぬいとり',
  ],
  13: [
    '黽|MÃNH|con ếch|べん',
    '鼎|ĐỈNH|cái vạc|かなえ',
    '鼓|CỔ|cái trống|つづみ',
    '鼠|THỬ|con chuột|ねずみ',
  ],
  14: ['鼻|TỴ|cái mũi|はな', '斉/齊|TỀ|ngang bằng|せい'],
  15: ['歯/齒|XỈ|răng|は'],
  16: ['竜/龍|LONG|con rồng|りゅう', '亀/龜|QUY|con rùa|かめ'],
  17: ['龠|DƯỢC|sáo ba lỗ|やく'],
};
